// HSN codes: building materials, interiors and fittings (cement, gypsum, paint, wood, tiles, glass, metal sections, hardware, plumbing, lighting fittings).
// One line per code:  code|description|name; another name; ...      (4 digits = heading, 6 digits = sub-heading; a line that starts with # is a comment)
// The descriptions follow the tariff (HS 2022); the names are what an item is called on a quote. A name that is just one common word ("door", "light") is given to one
// code only, the one most people mean. Where the 6-digit sub-headings were renumbered recently only the 4-digit heading is given.

export const GOODS_BUILDING = `
# ---------------------------------------------------------------- Cement, lime, sand, stone, bricks and blocks
2523|Portland cement, aluminous cement, slag cement and similar hydraulic cements|cement; cement bag; opc cement; ppc cement; portland cement; portland pozzolana cement; pozzolana cement; rapid hardening cement; waterproof cement; wall care cement
252321|White Portland cement|white cement; birla white; white portland cement; wall care white cement
252329|Portland cement other than white cement|opc; ppc; ordinary portland cement; grey cement
2520|Gypsum; anhydrite; plasters consisting of calcined gypsum or calcium sulphate|gypsum; gypsum powder; plaster of paris; pop powder; pop bag; calcined gypsum; gypsum plaster powder; wall plaster powder; gypsum plaster; ready mix plaster; pop
2505|Natural sands of all kinds|sand; river sand; construction sand; plastering sand; silica sand; filling sand; fine sand; coarse sand
2517|Pebbles, gravel, broken or crushed stone for concrete aggregates, road metalling or railway ballast|aggregate; stone aggregate; blue metal; gravel; crushed stone; jelly; stone chips; 20 mm aggregate; 40 mm aggregate; m sand; manufactured sand; crusher dust; ballast; road metal
2522|Quicklime, slaked lime and hydraulic lime|lime; quick lime; slaked lime; hydrated lime; lime powder; white lime; chuna
2515|Marble, travertine and other calcareous monumental or building stone, crude or roughly trimmed|marble block; raw marble; rough marble
2516|Granite, porphyry, basalt, sandstone and other monumental or building stone, crude or roughly trimmed|granite block; raw granite; rough granite; sandstone block
6802|Worked monumental or building stone and articles thereof|stone tile; stone slab; stone flooring; stone cladding; kota stone; sandstone tile; slate tile; natural stone; stone work material; stone panel; stone veneer
680221|Marble, travertine and alabaster, merely cut or sawn into slabs of a flat or even surface|marble; marble slab; marble tile; marble flooring; italian marble; indian marble; makrana marble; white marble; marble stone; marble counter top; marble top; marble skirting; marble sheet; onyx slab; travertine
680223|Granite, merely cut or sawn into slabs of a flat or even surface|granite; granite slab; granite tile; granite flooring; granite counter top; kitchen granite; kitchen platform granite; black granite; granite top; granite stone; granite skirting
680229|Other stone, merely cut or sawn into slabs of a flat or even surface|kota stone; sandstone slab; slate; slate stone; limestone slab; tandoor stone; shahabad stone; cuddapah slab; quartzite slab; natural stone slab
6904|Ceramic building bricks, flooring blocks, support or filler tiles|clay brick; red brick; building brick; brick; bricks; hollow clay brick; terracotta brick; flooring block; filler tile
6905|Roofing tiles, chimney pots, cowls, chimney liners, architectural ornaments and other ceramic constructional goods|roofing tile; clay roofing tile; mangalore tile; terracotta tile roof; ridge tile; chimney pot
681011|Building blocks and bricks of cement, concrete or artificial stone|concrete block; cement block; solid block; hollow block; aac block; autoclaved aerated concrete block; cement brick; fly ash block; cellular lightweight concrete block; clc block
681019|Tiles, flagstones, paving blocks and similar articles of cement, concrete or artificial stone|paver block; paving block; interlocking tile; interlocking paver; cement tile; concrete tile; kerb stone; cement flooring tile; terrazzo tile; chequered tile; cement jali; concrete jali; garden tile; cobble stone; quartz slab; quartz counter top; engineered stone; artificial stone slab; artificial marble
681091|Prefabricated structural components for building or civil engineering of cement, concrete or artificial stone|precast concrete; precast slab; precast wall; precast boundary wall; readymade compound wall; rcc pole; cement pole; precast panel; precast beam; precast column; concrete slab
681099|Other articles of cement, concrete or artificial stone|cement pipe; rcc pipe; concrete pipe; cement planter; concrete planter; concrete bench; cement pot; concrete product; cement product; manhole cover rcc; cement chajja
6811|Articles of asbestos-cement, of cellulose fibre-cement or the like|fibre cement board; cement board; fibre cement sheet; cement fibre board; cement sheet; calcium silicate board; asbestos cement sheet; ac sheet; cement roofing sheet; hardiflex; hardie board; cement ceiling board
681181|Corrugated sheets of asbestos-cement, cellulose fibre-cement or the like|corrugated cement sheet; ac roofing sheet; fibre cement roofing sheet; corrugated sheet cement
681182|Other sheets, panels, tiles and similar articles of cellulose fibre-cement or the like|fibre cement panel; cement panel; cladding board cement; cement partition board; cement fibre panel; magnesium oxide board; mgo board; calcium silicate sheet
6806|Slag wool, rock wool and similar mineral wools; exfoliated vermiculite, expanded clays and other heat-insulating, sound-insulating or sound-absorbing mineral materials|rock wool; rockwool; mineral wool; slag wool; thermal insulation material; vermiculite; expanded perlite; insulation board; acoustic insulation material; ceiling tile; false ceiling tile; grid ceiling tile; mineral fibre ceiling tile; mineral fibre tile; acoustic ceiling tile; armstrong ceiling
6809|Articles of plaster or of compositions based on plaster|gypsum product; plaster product
680911|Plasterboard, sheets, panels, tiles and similar articles, not ornamented, faced or reinforced with paper or paperboard only|gypsum board; plaster board; plasterboard; drywall board; dry wall board; false ceiling board; gypsum sheet; gypsum panel; gyproc board; gyproc; ceiling board; partition board; gypsum ceiling board; moisture resistant gypsum board; fire resistant gypsum board; regular gypsum board; gypsum tile; gypsum false ceiling board; gypsum wall board
680919|Other plasterboard, sheets, panels, tiles and similar articles of plaster, not ornamented|fibre reinforced gypsum board; glass fibre gypsum board; gypsum fibre board
680990|Other articles of plaster or compositions based on plaster|pop cornice; gypsum cornice; plaster cornice; pop moulding; ceiling rose; gypsum moulding; plaster moulding; ceiling medallion; gypsum cove; pop design; decorative plaster article
6907|Ceramic flags and paving, hearth or wall tiles; ceramic mosaic cubes and the like; finishing ceramics|tile; floor tile; wall tile; ceramic tile; ceramic floor tile; bathroom tile; kitchen tile; designer tile; outdoor tile; parking tile; elevation tile; subway tile; tiles
690721|Tiles with water absorption not exceeding 0.5 percent by weight (vitrified and porcelain tiles)|vitrified tile; porcelain tile; glazed vitrified tile; gvt; pgvt; polished vitrified tile; double charge tile; full body vitrified tile; nano tile; soluble salt tile; granite finish tile; slab tile; large format tile
690722|Tiles with water absorption exceeding 0.5 percent but not exceeding 10 percent by weight|semi vitrified tile; ceramic floor tile semi vitrified; floor ceramic tile
690723|Tiles with water absorption exceeding 10 percent by weight (glazed ceramic wall tiles)|glazed ceramic wall tile; digital wall tile; ceramic wall tile; wall ceramic tile; bathroom wall tile; kitchen wall tile; highlighter tile; decor tile
690730|Mosaic cubes and the like, other than those of 690740|mosaic tile; mosaic cube; ceramic mosaic; mosaic
690740|Finishing ceramics|skirting tile; ceramic skirting; border tile; ceramic border; ceramic trim; tile trim ceramic
6910|Ceramic sinks, wash basins, wash basin pedestals, baths, bidets, water closet pans, flushing cisterns, urinals and similar sanitary fixtures|sanitary ware; sanitaryware; ceramic sanitary ware; wash basin; basin; counter basin; table top basin; pedestal basin; wall hung basin; wc; commode; toilet; water closet; western toilet; indian toilet pan; squatting pan; urinal; ceramic sink; bidet; wall hung wc; one piece wc; two piece wc; concealed cistern ceramic; basin pedestal
# ---------------------------------------------------------------- Paint, putty, adhesive, sealant, chemicals
3209|Paints and varnishes based on synthetic polymers dispersed or dissolved in an aqueous medium|paint; wall paint; interior paint; exterior paint; emulsion; emulsion paint; acrylic emulsion; water based paint; plastic paint; acrylic paint; texture paint; textured paint; weatherproof paint; wall primer; water based primer; cement primer; acrylic primer; asian paints; berger paint; nerolac paint; ceiling paint; roof paint; waterproof paint; 20 ltr paint; paint bucket
3208|Paints and varnishes based on synthetic polymers dispersed or dissolved in a non-aqueous medium|enamel; enamel paint; synthetic enamel; oil paint; oil based paint; solvent based paint; pu paint; polyurethane paint; epoxy paint; epoxy coating; epoxy primer; polyurethane coating; pu coating; wood coating; wood finish; automotive paint; metal paint; anticorrosive paint; zinc primer; red oxide primer; metal primer; road marking paint; floor paint; heat resistant paint; fire retardant paint; duco paint; spray paint; aerosol paint
3210|Other paints and varnishes; prepared water pigments of a kind used for finishing leather|distemper; oil bound distemper; varnish; clear varnish; lacquer; wood polish; french polish; shellac; melamine polish; pu polish; nc polish; wood stain; wood varnish; polyurethane varnish; clear coat; clear lacquer
3214|Glaziers' putty, grafting putty, resin cements, caulking compounds and other mastics; painters' fillings; non-refractory surfacing preparations for facades, indoor walls, floors, ceilings|putty; wall putty; birla putty; acrylic putty; white cement putty; wall care putty; skim coat; filler; crack filler; wood putty; wood filler; gap filler; joint filler; textured coating; stucco; tile grout; grout; tile gap filler; epoxy grout
321410|Glaziers' putty, grafting putty, resin cements, caulking compounds and other mastics; painters' fillings|sealant; silicone sealant; caulk; caulking; mastic; polyurethane sealant; pu sealant; acrylic sealant; weatherproof sealant; glass sealant; construction sealant; sanitary sealant; silicone gun cartridge
3506|Prepared glues and other prepared adhesives not elsewhere specified|adhesive; glue; fevicol; synthetic resin adhesive; contact adhesive; araldite; epoxy adhesive; wood glue; pvac adhesive; fevikwik; cyanoacrylate; super glue; tile adhesive; tile fixing adhesive; tile bond; cement adhesive; pu adhesive; construction adhesive; mounting adhesive; gum; all purpose adhesive; fevicol sh; fevicol marine; dr fixit adhesive
3814|Organic composite solvents and thinners not elsewhere specified; prepared paint or varnish removers|thinner; paint thinner; nc thinner; pu thinner; epoxy thinner; paint remover; varnish remover; solvent thinner; turpentine substitute
382440|Prepared additives for cements, mortars or concretes|concrete admixture; admixture; mortar additive; plasticiser; plasticizer; integral waterproofing compound; waterproofing admixture; construction chemical; concrete additive; super plasticizer; bonding agent; bonding chemical; dr fixit; fosroc
3824|Prepared binders for foundry moulds or cores; chemical products and preparations of the chemical or allied industries not elsewhere specified|waterproofing chemical; waterproofing compound; waterproof coating; terrace waterproofing; waterproofing material; polymer coating; crystalline waterproofing; anti termite chemical; termite chemical; chemical coating
6807|Articles of asphalt or of similar material (for example petroleum bitumen or coal tar pitch)|bituminous membrane; waterproofing membrane; app membrane; sbs membrane; roofing felt; bitumen sheet; bitumen felt; bituminous felt
2715|Bituminous mixtures based on natural asphalt, natural bitumen, petroleum bitumen, mineral tar or mineral tar pitch|bitumen; bitumen emulsion; bitumen primer; bituminous coating; cutback bitumen; bitumen paint; asphalt; hot mix; bitumen drum
# ---------------------------------------------------------------- Wood and wood products
4412|Plywood, veneered panels and similar laminated wood|plywood; ply; marine plywood; commercial plywood; waterproof plywood; shuttering ply; shuttering plywood; block board; blockboard; laminated board; veneered board; ply board; film faced plywood; bwp plywood; bwr plywood; mr plywood; flexible plywood; veneered plywood; plywood sheet; 19 mm plywood; 18 mm plywood; 12 mm plywood; greenply; century ply
4410|Particle board, oriented strand board (OSB) and similar board of wood or other ligneous materials|particle board; chipboard; chip board; prelam board; pre laminated board; prelaminated particle board; osb; osb board; pre lam particle board; laminated particle board
4411|Fibreboard of wood or other ligneous materials|mdf; mdf board; mdf sheet; hdhmr; hdhmr board; hdf; hdf board; prelam mdf; fibre board; hardboard; fluted mdf panel; mdf fluted panel; mdf wall panel; mdf panel; pre laminated mdf; laminated mdf; plain mdf; mdf 18 mm; mdf 12 mm; exterior mdf; moisture resistant mdf
4408|Sheets for veneering, sheets for plywood and other wood sawn lengthwise, sliced or peeled, of a thickness not exceeding 6 mm|veneer; wood veneer; natural veneer; veneer sheet; teak veneer; reconstituted veneer; engineered veneer; wood laminate veneer; veneer roll; oak veneer; walnut veneer; ash veneer; wenge veneer
4407|Wood sawn or chipped lengthwise, sliced or peeled, of a thickness exceeding 6 mm|timber; teak wood; teak; sawn timber; wooden plank; sal wood; pine wood; hardwood; softwood; wooden batten; wooden beam; wood log sawn; wooden rafter; wooden section; wooden patti; rubber wood; meranti; sheesham; mango wood; neem wood; wooden stick
4409|Wood continuously shaped along any of its edges or faces (flooring strips, beading, moulding, skirting)|wooden skirting; wooden moulding; wood moulding; wooden beading; wooden profile; wooden cornice; wooden flooring strip; skirting; wooden cove; wooden fluted strip; wooden beading profile; tongue and groove board; wooden cladding board
4418|Builders' joinery and carpentry of wood, including cellular wood panels, assembled flooring panels, shingles and shakes|wooden door; wooden window; door frame; wooden frame door; door shutter; flush door; panel door; wooden flooring; laminate flooring; engineered wood flooring; wooden floor; parquet; wooden panel; wooden staircase; wooden pergola; wooden shutter; wooden louvers; wooden cladding; wooden deck; decking; wooden railing; teak door; main door; door; doors; wooden door frame; laminated door; laminate door; flooring laminate; wooden floor tile
4414|Wooden frames for paintings, photographs, mirrors or similar objects|photo frame; picture frame; wooden frame; mirror frame; wall frame; frame; photo frames; art frame; certificate frame; wooden photo frame; wooden mirror frame; frames; collage frame; wall photo frame; wooden picture frame
4420|Wood marquetry and inlaid wood; caskets and cases for jewellery or cutlery, and similar articles, of wood; statuettes and other ornaments, of wood; wooden articles of furniture not falling in chapter 94|wooden ornament; wooden showpiece; wooden statue; wood carving; wooden wall art; wooden decor; wooden decorative item; jewellery box wooden; wooden box decorative; wooden idol; wooden handicraft; wooden carving panel; wooden jali; wooden wall hanging
4421|Other articles of wood|wooden hanger; wooden article; wooden name plate; wooden shelf; wooden bracket; wooden hook; wooden stick article; wooden peg; clothes hanger; wooden ladder; wooden handle; wooden spoon; wooden tray
4415|Packing cases, boxes, crates, drums and similar packings, of wood; cable-drums of wood; pallets, box pallets and other load boards, of wood|wooden box; wooden crate; pallet; wooden pallet; packing box wooden; wooden packing case; cable drum wooden; wooden drum
4501|Natural cork, raw or simply prepared; waste cork; crushed, granulated or ground cork|cork; cork sheet; cork board; cork roll; cork flooring; cork tile; cork wall tile
# ---------------------------------------------------------------- Plastics for building: pipes, panels, sheets, flooring, tanks, sanitary ware
3917|Tubes, pipes and hoses, and fittings therefor, of plastics|pipe; plastic pipe; water pipe; plumbing pipe; drainage pipe; sewer pipe; swr pipe; column pipe; garden pipe
391721|Rigid tubes, pipes and hoses of polymers of ethylene|hdpe pipe; pe pipe; polyethylene pipe; hdpe coil; hdpe duct; pe duct; dwc pipe; double wall corrugated pipe; ldpe pipe; drip pipe; irrigation pipe; agricultural pipe; mdpe pipe
391722|Rigid tubes, pipes and hoses of polymers of propylene|ppr pipe; pp pipe; polypropylene pipe; ppr plumbing pipe; ppr hot water pipe
391723|Rigid tubes, pipes and hoses of polymers of vinyl chloride|pvc pipe; upvc pipe; cpvc pipe; pvc conduit; pvc electrical conduit; electrical conduit; conduit pipe; conduit; rigid conduit; pvc water pipe; pvc drainage pipe; pvc swr pipe; pvc casing pipe; borewell casing pipe; pvc column pipe; pvc rain water pipe; pvc rwp; ashirvad pipe; supreme pipe; finolex pipe; astral pipe; upvc pipe fitting pipe; pipe 25 mm; pipe 20 mm
391729|Rigid tubes, pipes and hoses of other plastics|abs pipe; frp pipe; plastic rigid pipe; pe rt pipe; pex pipe; pert pipe
391733|Other flexible tubes, pipes and hoses, not reinforced, with fittings|flexible conduit; corrugated conduit; flexible pipe; corrugated pipe; flexible hose; pvc flexible pipe; pvc hose; garden hose pipe; hose pipe; water hose; flexible corrugated pipe; spiral hose; braided hose; connection pipe; flexible connector
391739|Other tubes, pipes and hoses, not reinforced, without fittings|pvc layflat hose; layflat pipe; delivery hose; suction hose; transparent hose; pvc transparent pipe; silicone tube; plastic tubing; plastic tube; pu tube
391740|Fittings of plastics for tubes, pipes and hoses|pipe fitting; pvc fitting; elbow; bend; tee; coupler; coupling; reducer; end cap; pipe clamp; saddle clamp; pvc elbow; pvc tee; pvc bend; cpvc fitting; ppr fitting; upvc fitting; swr fitting; conduit fitting; conduit bend; junction box pvc; pvc junction box; pvc box; pvc clip; conduit clip; pipe clip; union; pvc union; pipe nipple; pvc adapter; water pipe fitting
3918|Floor coverings of plastics, whether or not self-adhesive, in rolls or in the form of tiles; wall or ceiling coverings of plastics|vinyl flooring; pvc flooring; spc flooring; lvt flooring; vinyl tile; pvc floor tile; floor covering; vinyl floor; vinyl plank; spc plank; luxury vinyl tile; rigid core flooring; pvc floor roll; vinyl roll; floor vinyl; plastic flooring; vinyl sheet flooring; wall covering plastic; pvc wall covering; pvc wall sheet; pvc wallpaper; vinyl wall covering; pvc ceiling covering; wall vinyl; vinyl sheet
3919|Self-adhesive plates, sheets, film, foil, tape, strip and other flat shapes, of plastics, whether or not in rolls|adhesive tape; self adhesive tape; bopp tape; packing tape; double sided tape; masking tape; self adhesive vinyl; vinyl sticker; sticker roll; sticker sheet; self adhesive sheet; vinyl film; adhesive film; window film; frosted film; glass film; sun control film; one way vision film; decorative film; wrapping film adhesive; pvc tape; insulation tape; electrical tape; foam tape; reflective tape; cello tape; scotch tape
3920|Other plates, sheets, film, foil and strip, of plastics, non-cellular and not reinforced, laminated, supported or similarly combined with other materials|plastic sheet; pvc sheet; rigid pvc sheet; transparent sheet; clear sheet; plastic film; polythene sheet; pe sheet; vinyl sheet plain; ps sheet; plastic board; pvc board; foam pvc board; pvc foam board; sunboard; celuka board; wpc board; forex sheet; pvc forex; plastic laminate sheet; frp sheet; flexible sheet
392051|Plates and sheets of polymethyl methacrylate (acrylic)|acrylic sheet; acrylic board; perspex; plexiglass; acrylic; acrylic panel; acrylic glass; acrylic mirror; mirror acrylic; acrylic letters sheet; acrylic cut sheet; 3 mm acrylic; 5 mm acrylic
392061|Plates and sheets of polycarbonates|polycarbonate sheet; pc sheet; polycarbonate roofing sheet; multiwall polycarbonate; solid polycarbonate sheet; polycarbonate panel; lexan; twin wall polycarbonate; skylight sheet
392062|Plates and sheets of polyethylene terephthalate|pet sheet; pet film; pet board; pet felt; pet sheet clear; polyester sheet
3921|Other plates, sheets, film, foil and strip, of plastics|decorative laminate; laminate sheet; sunmica; high pressure laminate; hpl; hpl sheet; compact laminate; laminate; laminates; acp; acp sheet; aluminium composite panel; aluminium composite sheet; composite panel; alucobond; wpc sheet; foam sheet; pvc foam sheet; eva foam sheet; foam board; epe foam; xpe foam; cellular sheet; plastic foam; fluted laminate; membrane press film; pvc membrane film
392111|Cellular plates, sheets, film, foil and strip of polymers of styrene|thermocol; thermocol sheet; eps sheet; eps board; xps board; xps sheet; polystyrene foam; thermocole; expanded polystyrene; styrofoam; thermocol insulation; polystyrene board
392113|Cellular plates, sheets, film, foil and strip of polyurethanes|pu foam; pu foam sheet; polyurethane foam; foam sheet pu; puf panel; pu panel; polyurethane panel; puf insulation; sponge sheet; foam rubber sheet; acoustic foam; foam padding; mattress foam; pu foam roll; memory foam sheet
3922|Baths, shower-baths, sinks, wash-basins, bidets, lavatory pans, seats and covers, flushing cisterns and similar sanitary ware, of plastics|plastic sanitary ware; flush tank; cistern; concealed cistern; wc cistern; water closet cistern; flushing cistern; toilet seat cover; seat cover; plastic wash basin; shower tray; bath tub plastic; acrylic bathtub; plastic urinal; flush cistern; pvc cistern
3924|Tableware, kitchenware, other household articles and hygienic or toilet articles, of plastics|plastic bucket; bucket; mug; plastic mug; plastic tub; plastic basket; laundry basket; plastic bin; dustbin; waste bin; plastic jug; water jug; plastic container; plastic tray; plastic plate; plastic bowl; plastic glass; plastic spoon; plastic hanger; storage box plastic; plastic stool small; soap dispenser plastic; plastic bottle household; water bottle plastic; plastic tableware; plastic kitchenware
3925|Builders' ware of plastics not elsewhere specified or included|pvc wall panel; wpc wall panel; wpc fluted panel; fluted panel; fluted wall panel; wall panel; wall panelling; wall panel pvc; pvc ceiling panel; pvc cladding; plastic wall cladding; wall cladding; louvers pvc; pvc louvers; charcoal louver; charcoal louver panel; bamboo charcoal panel; bamboo charcoal board; ps panel; polystyrene wall panel; 3d wall panel; 3d panel; pu stone panel; pu panel stone; stone veneer panel; wpc louver; wpc cladding; pvc ceiling; pvc false ceiling; pvc tile ceiling; ceiling panel; wall board plastic; plastic skirting; pvc skirting; pvc profile; pvc trim; pvc corner; pvc moulding; skirting pvc; plastic beading; soffit panel
392510|Reservoirs, tanks, vats and similar containers, of a capacity exceeding 300 litres, of plastics|water tank; plastic tank; pvc tank; sintex tank; overhead tank; loft tank; storage tank; tank; roto tank; drum tank; syntex tank; 1000 litre tank; 500 litre tank; septic tank plastic; underground tank
392520|Doors, windows and their frames and thresholds for doors, of plastics|pvc door; upvc door; upvc window; pvc window; plastic door; plastic window; upvc sliding window; upvc sliding door; upvc casement window; pvc door frame; plastic door frame; bathroom pvc door; frp door; wpc door; wpc door frame; upvc fixed window; upvc ventilator; pvc ventilator
392530|Shutters, blinds (including Venetian blinds) and similar articles and parts thereof, of plastics|pvc shutter; plastic shutter; window shutter; pvc window shutter; pvc blind; plastic blind; pvc venetian blind; louvre shutter; pvc roller shutter; plastic roller blind; shutters; shutter pvc; pvc folding door; accordion door; pvc sliding folding door; pvc louvre; plantation shutter; vertical blind pvc
3926|Other articles of plastics and articles of other materials of headings 3901 to 3914|plastic article; plastic product; plastic item; plastic fitting; plastic accessory; plastic handle; plastic knob; plastic clip; plastic hook; plastic channel; plastic spacer; tile spacer; tile spacers; rawl plug; wall plug; plastic anchor; plastic wall plug; nylon plug; plastic cable tie; cable tie; cable clip; cable channel; casing and capping; pvc casing; casing capping; wire duct; cable duct; trunking; pvc trunking; cable trunking plastic; wiring duct
392690|Other articles of plastics (other)|plastic photo frame; plastic frame; plastic letter; plastic sign; plastic number plate; plastic name plate; plastic plant pot; plastic planter; plastic pot; plastic flower pot; plastic decoration; plastic ornament; plastic idol; pvc strip curtain; plastic strip curtain; door strip curtain; plastic gutter; plastic channel gutter
3916|Monofilament of which any cross-sectional dimension exceeds 1 mm, rods, sticks and profile shapes, of plastics|plastic profile; pvc profile section; pvc rod; plastic rod; nylon rod; plastic beading section; u channel plastic; plastic angle; plastic edge; edge band; edge banding; edge banding tape; pvc edge band; pvc edge banding; abs edge band; pvc beading
4016|Other articles of vulcanised rubber other than hard rubber|rubber mat; rubber flooring; rubber tile; gym flooring; rubber sheet; rubber gasket; rubber seal; rubber stopper; door stopper rubber; rubber bumper; rubber washer; rubber strip; rubber profile; door seal; epdm gasket; rubber beading; rubber door mat; anti slip mat; rubber matting; rubber floor mat; car mat
# ---------------------------------------------------------------- Glass and mirrors
7005|Float glass and surface ground or polished glass, in sheets, whether or not having an absorbent, reflecting or non-reflecting layer, but not otherwise worked|float glass; clear glass; plain glass; tinted glass; reflective glass; glass sheet; glass pane; window glass; frosted glass; clear float glass; bronze glass; green glass sheet; blue glass; grey glass; tinted float glass; glass 5 mm; glass 8 mm; glass 12 mm; raw glass; plain float glass
7006|Glass of heading 7003, 7004 or 7005, bent, edge-worked, engraved, drilled, enamelled or otherwise worked, but not framed or fitted with other materials|bevelled glass; edge polished glass; drilled glass; back painted glass; lacquered glass; printed glass; etched glass; acid etched glass; digital printed glass; designer glass; glass with design; sand blasted glass; sandblasted glass; engraved glass; ceramic frit glass; cut to size glass; bent glass; curved glass; glass cutting; polished glass; glass edge polishing; coated glass
7007|Safety glass, consisting of toughened (tempered) or laminated glass|toughened glass; tempered glass; safety glass; glass partition; glass door; glass railing; glass balustrade; shower glass; shower partition; glass shelf; glass shelves; glass top; table glass top; glass panel; toughened glass 10 mm; toughened glass 12 mm; toughened glass 8 mm; toughened glass door; frameless glass door; frameless glass; glass cabin; glass office partition; glass staircase railing; glass canopy; glass cladding
700729|Laminated safety glass, other than for vehicles|laminated glass; pvb laminated glass; sentry glass; laminated toughened glass; acoustic laminated glass; bulletproof glass; sgp glass
7008|Multiple-walled insulating units of glass|double glazed unit; insulating glass; igu; double glazing; double glazed glass; insulated glass unit; triple glazing; dgu; low e glass unit
7009|Glass mirrors, whether or not framed, including rear-view mirrors|mirror; wall mirror; glass mirror; bathroom mirror; decorative mirror; led mirror; illuminated mirror; dressing mirror; framed mirror; round mirror; full length mirror; vanity mirror; mirror glass; silver mirror; antique mirror; smart mirror; touch sensor mirror; sunburst mirror; mirror panel; mirror 5 mm; mirror tile; wall mirrors
7016|Paving blocks, slabs, bricks, squares, tiles and other articles of pressed or moulded glass, whether or not wired, of a kind used for building or construction purposes; glass cubes and other glass smallwares for mosaics|glass tile; glass mosaic; glass block; glass brick; glass paver; glass mosaic tile; crystal tile; glass cubes; glass wall tile
7019|Glass fibres (including glass wool) and articles thereof (for example, yarn, woven fabrics)|glass wool; fibre glass; fiberglass; glass fibre; glass fibre mat; chopped strand mat; csm; fibreglass cloth; glass cloth; fibre glass insulation; glass fibre fabric; fibreglass mesh; glass fibre mesh; roving
7013|Glassware of a kind used for table, kitchen, toilet, office, indoor decoration or similar purposes|glassware; glass vase; glass bowl; glass decor; crystal; glass jar; glass bottle decor; glass showpiece; decorative glass; glass tumbler; drinking glass; water glass; glass jug; glass plate; glass candle holder; crystal vase; glass lamp shade; glass dish
7020|Other articles of glass|glass article; glass product; glass tube article; glass rod; glass hook; glass accessory; glass knob; glass handle
# ---------------------------------------------------------------- Iron, steel, aluminium and other metal for building
7210|Flat-rolled products of iron or non-alloy steel, of a width of 600 mm or more, clad, plated or coated|coated sheet; coated coil; coated steel
721041|Flat-rolled products of iron or non-alloy steel, plated or coated with zinc, corrugated|gi corrugated sheet; galvanised corrugated sheet; corrugated sheet; gc sheet; corrugated gi sheet; corrugated roofing sheet; roofing sheet; gi roofing sheet; metal roofing sheet; profile sheet; trapezoidal sheet; roofing profile sheet; tin sheet; tin roofing
721049|Flat-rolled products of iron or non-alloy steel, otherwise plated or coated with zinc|gi sheet; galvanised sheet; galvanized sheet; gp sheet; galvanised plain sheet; gi plain sheet; galvanised iron sheet; gi coil; galvanised coil; gi flat sheet; zinc coated sheet; galvalume sheet; gi 22 gauge; gi 24 gauge
721070|Flat-rolled products of iron or non-alloy steel, painted, varnished or coated with plastics|color coated sheet; colour coated sheet; ppgi; ppgi sheet; ppgl sheet; prepainted sheet; pre painted galvanised sheet; colour coated roofing sheet; coloured roofing sheet; ppgi coil; painted sheet
7208|Flat-rolled products of iron or non-alloy steel, of a width of 600 mm or more, hot-rolled, not clad, plated or coated|ms sheet; ms plate; hot rolled sheet; hr sheet; hr coil; hot rolled coil; mild steel sheet; mild steel plate; steel plate; steel sheet; chequered plate; checkered plate; ms chequered sheet; boiler plate; hr plate; iron plate; iron sheet; ms flat sheet
7209|Flat-rolled products of iron or non-alloy steel, of a width of 600 mm or more, cold-rolled, not clad, plated or coated|cold rolled sheet; cr sheet; cr coil; cold rolled coil; cold rolled steel; crca sheet; crca coil; cr sheet 18 gauge; mild steel cr sheet
7211|Flat-rolled products of iron or non-alloy steel, of a width of less than 600 mm, not clad, plated or coated|ms flat; ms strip; steel strip; flat bar; ms flat bar; steel flat; hot rolled strip; cold rolled strip; iron flat; steel flats; mild steel flat; iron strip; hoop iron; gi strip
7213|Bars and rods, hot-rolled, in irregularly wound coils, of iron or non-alloy steel|wire rod; steel wire rod; tmt coil; ms wire rod; rebar coil; bar in coil; coil bar; tmt bar coil; wire rod coil
7214|Other bars and rods of iron or non-alloy steel, not further worked than forged, hot-rolled, hot-drawn or hot-extruded|tmt; tmt bar; tmt steel; rebar; reinforcement bar; reinforcement steel; steel bar; mild steel bar; ms rod; ms bar; round bar; iron rod; construction steel; fe 500 bar; fe 550 bar; steel rod; iron bar; steel rebar; 8 mm bar; 10 mm bar; 12 mm bar; 16 mm bar; ms round; ms square bar; square bar; steel round bar
7216|Angles, shapes and sections of iron or non-alloy steel|angle; channel; ms angle; ms channel; i beam; h beam; ismb; ismc; isa; steel angle; steel channel; steel section; steel beam; mild steel angle; mild steel channel; gi channel; ceiling channel; main channel; c channel; omega channel; furring channel; perimeter channel; gi angle; l angle; stud; track channel; metal stud; drywall stud; gi stud and track; gi section; gi c channel; t section; z section; z purlin; c purlin; purlin; joist; steel joist; tee section; ceiling section; ceiling grid; t grid; main tee; cross tee; wall angle
7217|Wire of iron or non-alloy steel|gi wire; binding wire; iron wire; steel wire; ms wire; galvanised wire; galvanized wire; barbed wire iron; chain link wire; mild steel wire; annealed wire; hanger wire; ceiling hanger wire; suspension wire; steel rope wire; fencing wire; welding wire; tying wire; black annealed wire
7304|Tubes, pipes and hollow profiles, seamless, of iron or steel|seamless pipe; seamless tube; boiler tube; honed tube; cylinder tube; hydraulic tube; ss seamless pipe; seamless steel pipe; api pipe; line pipe seamless
7306|Other tubes, pipes and hollow profiles (for example, open seam or welded, riveted or similarly closed), of iron or steel|steel pipe; ms pipe; gi pipe; erw pipe; hollow section; pipe steel; welded pipe; iron pipe; ms tube; steel tube; gi tube; round pipe; mild steel pipe; galvanised pipe; galvanized pipe; ss pipe; stainless steel pipe; ss tube; pipe 1 inch; pipe 2 inch; scaffolding pipe; ms round pipe; ms pipe 25 mm
730661|Other welded tubes, pipes and hollow profiles of square or rectangular cross-section, of iron or non-alloy steel|square pipe; rectangular pipe; box pipe; ms square pipe; ms rectangular pipe; gi square pipe; gi rectangular pipe; square tube; rectangular tube; ms box; box section; hollow square; rhs; shs; ms hollow section; steel box pipe; steel square pipe; ss square pipe; ss rectangular pipe; ms square tube; rectangular tube steel; gi box section; pipe square 25 mm; pipe square 40 mm
7307|Tube or pipe fittings (for example, couplings, elbows, sleeves) of iron or steel|flange; elbow steel; steel fitting; gi fitting; gi elbow; gi socket; gi tee; gi nipple; gi union; ms flange; ms elbow; ss fitting; pipe fitting steel; coupling steel; reducer steel; ss elbow; ss flange; gi bend; threaded fitting; welded fitting; pipe bend steel; pipe cap steel; pipe clamp steel; u clamp; pipe support
7308|Structures (excluding prefabricated buildings of heading 9406) and parts of structures, of iron or steel; plates, rods, angles, shapes, sections, tubes and the like, prepared for use in structures, of iron or steel|steel structure; structural steel; fabricated steel; fabrication; steel fabrication; ms fabrication; ms structure; steel frame; steel framework; shed structure; pre engineered building; peb structure; roof truss; steel truss; steel support; steel bracket; ms bracket; gi framework; gi frame; gi frame work; steel stand; ms stand; ms frame; metal frame; metal structure; metal framework; truss; steel column; steel gantry; ms gantry; steel platform; mezzanine floor; mezzanine; steel staircase; ms staircase; metal staircase; ms canopy; steel canopy; steel pergola; metal pergola; ms gazebo; ms pole; steel pole; iron pole; pole; gi pole; street light pole; light pole; lamp post; high mast pole; octagonal pole; flag pole; flagpole; steel mast; tower; lattice tower; antenna tower; telecom tower; transmission tower; ms tower
730830|Doors, windows and their frames and thresholds for doors, of iron or steel|steel door; iron door; steel window; ms window; ms door; fire door; fire rated door; steel door frame; metal door; metal door frame; rolling shutter; roller shutter; steel shutter; ms shutter; gi shutter; shutter door; collapsible gate; collapsible door; steel gate; ms gate; iron gate; main gate; sliding gate; swing gate; folding gate; steel window frame; ms window frame; security door; safety door; steel security door; metal window; metal gate; boundary gate; grill door; iron grill door; ms grill door; ms grill; window grill; iron grill; safety grill; steel grill; gate; grill; gates; grills; ss gate; ss door; ss window
730840|Equipment for scaffolding, shuttering, propping or pit-propping, of iron or steel|scaffolding; scaffolding material; scaffold; cuplock; cuplock scaffolding; cuplock system; props; steel prop; adjustable prop; acrow prop; steel centering; steel shuttering; shuttering plate; centering plate; shuttering material; formwork; steel formwork; ms shuttering; scaffolding pipe set; scaffolding frame; h frame scaffolding; steel staging; steel jack; base jack; u head jack; scaffold clamp
730890|Other structures and parts of structures, of iron or steel|steel railing; ms railing; staircase railing; steel handrail; iron railing; ms balcony railing; steel balustrade; iron balustrade; ss railing; stainless steel railing; ss handrail; handrail; hand rail; balcony railing; stair railing; gate pillar; steel pillar; ss pillar; steel decorative panel; metal jali; ms jali; steel jali; metal screen; decorative screen metal; metal partition; steel partition; steel cladding; metal cladding; metal panel; metal wall panel; steel wall panel; metal ceiling; metal false ceiling; metal ceiling tile; metal louvers; steel louvers; louvers; louver; louvre; perforated panel; perforated sheet panel; cnc cut panel; laser cut panel; laser cut jali; cnc jali; mild steel jali
7318|Screws, bolts, nuts, coach screws, screw hooks, rivets, cotters, cotter-pins, washers and similar articles, of iron or steel|screw; screws; bolt; nut; washer; anchor bolt; fastener; fasteners; rivet; self drilling screw; drywall screw; gypsum screw; gi screw; ms screw; ss screw; nut and bolt; nuts and bolts; bolt and nut; hex bolt; hex nut; allen bolt; allen key bolt; grub screw; machine screw; fischer anchor; anchor fastener; expansion bolt; expansion anchor; wedge anchor; chemical anchor bolt; hilti anchor; j bolt; u bolt; stud bolt; threaded rod; threaded bar; all thread rod; hanger bolt; eye bolt; carriage bolt; foundation bolt; wood screw; self tapping screw; countersunk screw; csk screw; pan head screw; screw 1 inch; screw 2 inch; screw box
7317|Nails, tacks, drawing pins, corrugated nails, staples and similar articles, of iron or steel|nail; nails; wire nail; iron nail; steel nail; concrete nail; cut nail; staple; staples; staple pin; stapler pin; tacks; pin; u pin; brad nail; finishing nail; panel pin; clout nail; roofing nail; gun nail; brad pin; nail gun pin
7314|Cloth (including endless bands), grill, netting and fencing, of iron or steel wire; expanded metal of iron or steel|wire mesh; welded wire mesh; chain link fencing; chain link; fence; fencing; fencing mesh; weld mesh; gi wire mesh; ss wire mesh; insect mesh; mosquito mesh; mosquito net metal; expanded metal; expanded mesh; steel mesh; gi mesh; wire netting; hexagonal netting; bird net metal; bird mesh; crimped wire mesh; woven wire mesh; reinforcement mesh; brc mesh; weld mesh sheet; barbed wire fencing; razor wire; concertina wire
7323|Table, kitchen or other household articles and parts thereof, of iron or steel; iron or steel wool; pot scourers and scouring or polishing pads, gloves and the like, of iron or steel|steel utensil; kitchen utensil; steel kitchenware; stainless steel utensil; ss utensil; steel container; steel tiffin; steel bottle; steel glass; steel plate; steel bowl; steel tray; steel jug; steel basket; steel rack kitchen; kitchen basket; kitchen tray; pot scourer; steel wool; scrubber; cutlery stand; dish rack; kitchen rack; utensil rack; kitchen trolley steel; kitchen organiser; kitchen basket modular; pull out basket; tandem basket; cutlery basket
7324|Sanitary ware and parts thereof, of iron or steel|kitchen sink; ss sink; stainless steel sink; sink; steel sink; single bowl sink; double bowl sink; ss kitchen sink; sink with drainboard; wash basin steel; steel wash basin; bath tub steel; steel bathtub; sink 24 x 18; sink 37 x 18; ss sink 304
7326|Other articles of iron or steel|steel article; iron article; steel product; iron product; ms product; ms article; steel hook; steel clip; steel clamp; steel bracket small; iron bracket; iron hook; shelf bracket; wall bracket; steel hanger; ms hanger; steel chain decorative; iron chain; decorative iron; wrought iron; wrought iron work; iron art; metal art; steel art; ms art; iron decor; steel wall art; cable tray; ladder rack; cable ladder; steel cable tray; gi cable tray; perforated cable tray; steel box; ms box; steel ladder; ms ladder; iron ladder; steel trolley; ms trolley; steel stand small; planter stand; steel planter; ms planter
7604|Aluminium bars, rods and profiles|aluminium section; aluminium profile; aluminium extrusion; aluminium channel; aluminium angle; aluminium bar; aluminium rod; aluminium flat; aluminium t section; aluminium u channel; aluminium l angle; aluminium box section; aluminium square pipe; aluminium rectangular section; aluminium frame section; aluminium door section; aluminium window section; aluminium partition section; aluminium track; aluminium sliding track; led aluminium profile; led profile; aluminium led profile; strip profile; profile light aluminium; aluminium tile trim; tile profile aluminium; aluminium skirting; aluminium beading
7606|Aluminium plates, sheets and strip, of a thickness exceeding 0.2 mm|aluminium sheet; aluminium plate; aluminium coil; aluminium roll; embossed aluminium sheet; aluminium chequered sheet; aluminium composite? plate; aluminium roofing sheet; aluminium flat sheet; aluminium strip; aluminium perforated sheet; aluminium cladding sheet; aluminium panel sheet; aluminium cut sheet; aluminium ceiling; aluminium false ceiling; aluminium ceiling tile; aluminium clip in ceiling; aluminium plank ceiling; aluminium linear ceiling; aluminium baffle ceiling; aluminium grid ceiling; aluminium honeycomb panel; aluminium solid panel; aluminium wall panel
7608|Aluminium tubes and pipes|aluminium pipe; aluminium tube; aluminium round pipe; aluminium round tube; aluminium hollow section; aluminium handrail pipe; aluminium curtain rod; aluminium railing pipe
7610|Aluminium structures (excluding prefabricated buildings of heading 9406) and parts of structures; aluminium plates, rods, profiles, tubes and the like, prepared for use in structures|aluminium structure; aluminium fabrication; aluminium framework; aluminium frame; aluminium glazing system; aluminium curtain wall; aluminium facade; aluminium cladding; aluminium partition; aluminium office partition; aluminium glass partition; aluminium louvers; aluminium louvre; aluminium canopy; aluminium pergola; aluminium railing; aluminium handrail; aluminium balustrade; aluminium pillar; aluminium grill; aluminium jali; aluminium shutter; aluminium gate; aluminium cabin; aluminium kitchen frame; aluminium wardrobe frame; aluminium shelf frame; aluminium hanging frame; aluminium shop front; aluminium storefront
761010|Aluminium doors, windows and their frames and thresholds for doors|aluminium door; aluminium window; aluminium sliding window; aluminium sliding door; aluminium casement window; aluminium fixed window; aluminium folding door; aluminium french door; aluminium swing door; aluminium bathroom door; aluminium ventilator; aluminium door frame; aluminium window frame; aluminium fixed glass; aluminium louver window; aluminium bifold door; aluminium slider; aluminium glass door; aluminium glass window; aluminium mosquito net window; aluminium sliding window with net
7615|Table, kitchen or other household articles and parts thereof, of aluminium; sanitary ware of aluminium|aluminium utensil; aluminium vessel; aluminium cookware; aluminium container; aluminium tray; aluminium kitchenware; aluminium bowl; aluminium pot; aluminium pan; aluminium kadai; aluminium handi; aluminium kettle; aluminium lunch box; aluminium bottle
7616|Other articles of aluminium|aluminium article; aluminium product; aluminium accessory; aluminium ladder; aluminium ladders; aluminium step ladder; aluminium bracket; aluminium hook; aluminium clip; aluminium hanger; aluminium handle; aluminium knob; aluminium plank; aluminium scaffolding; aluminium trolley; aluminium stand; aluminium shelf; aluminium rack; aluminium wall shelf; aluminium letters; aluminium name plate; aluminium nameplate; aluminium sign
7411|Copper tubes and pipes|copper pipe; copper tube; copper pipe ac; ac copper pipe; refrigeration copper pipe; copper coil pipe; brass pipe; copper tubing; copper line set; ac pipe copper; copper pipe 1/4; copper pipe 3/8; copper pipe 5/8
7412|Copper tube or pipe fittings (for example, couplings, elbows, sleeves)|copper fitting; copper elbow; copper coupling; copper tee; brass fitting; brass elbow; brass coupling; brass nipple; brass union; brass reducer; copper reducer; brass pipe fitting; compression fitting; flare fitting
7418|Table, kitchen or other household articles and parts thereof, of copper; pot scourers and scouring or polishing pads, gloves and the like, of copper; sanitary ware and parts thereof, of copper|copper utensil; brass utensil; copper vessel; brass vessel; copper bottle; copper jug; copper glass; brass kitchenware; copper kitchenware; brass bowl; brass plate; copper pot; copper handi; brass diya; brass lamp; brass bell; copper sink; brass sink
7419|Other articles of copper|copper article; copper product; brass article; brass product; copper wall art; brass wall art; brass decor; copper decor; brass handle; brass hook; brass accessory; copper accessory; brass sheet article
# ---------------------------------------------------------------- Locks, hardware and fittings
8301|Padlocks and locks (of a kind used for motor vehicles or furniture), clasps and frames with clasps incorporating locks, of base metal; keys for any of the foregoing articles, of base metal|lock; locks; key; keys; padlock; door lock; mortise lock; cylindrical lock; rim lock; cabinet lock; drawer lock; furniture lock; cupboard lock; wardrobe lock; locker lock; mortise lock set; lock set; main door lock; gate lock; shutter lock; digital lock; smart lock; electronic lock; biometric lock; fingerprint lock; fingerprint door lock; smart door lock; digital door lock; keyless lock; rfid lock; card lock; hotel lock; face recognition lock; wifi door lock; pin code lock; password lock; code lock; combination lock; cam lock; glass door lock; patch fitting lock; floor spring lock; sliding door lock; latch; door latch; tower bolt; door bolt; aldrop; aldrop lock; door chain; hasp; hasp and staple
8302|Base metal mountings, fittings and similar articles suitable for furniture, doors, staircases, windows, blinds, coachwork, saddlery, trunks, chests, caskets or the like; hat-racks, hat-pegs, brackets and similar fixtures; castors; automatic door-closers of base metal|hardware; furniture hardware; door hardware; builders hardware; fittings; furniture fittings; door fittings; window fittings; cabinet hardware; kitchen hardware; modular kitchen hardware; wardrobe hardware; interior hardware
830210|Hinges of any kind and parts thereof, of base metal|hinge; hinges; door hinge; cabinet hinge; soft close hinge; hydraulic hinge; concealed hinge; piano hinge; butt hinge; furniture hinge; glass door hinge; pivot hinge; cabinet hinges; clip on hinge; self closing hinge; slide on hinge; kitchen hinge; spring hinge; floor spring; hinge pin; wardrobe hinge
830220|Castors of base metal|castor; castors; caster; casters; wheel castor; furniture castor; trolley wheel castor; swivel castor; chair castor; castor wheel; furniture wheel; heavy duty castor
830241|Other mountings, fittings and similar articles suitable for buildings, of base metal|door handle; main door handle; pull handle; door pull; door knob; mortise handle; lever handle; door stopper; door stop; door holder; door guard; door eye; door viewer; peephole; door catch; magnetic catch; door buffer; window handle; window latch; window stay; window stopper; casement stay; window fitting; door fitting; sliding door fitting; sliding door roller; sliding track roller; sliding gear; sliding system; glass door fitting; patch fitting; glass door handle; glass handle; ss handle; brass handle; ss pull handle; entrance handle; towel rod; towel rail; towel holder; towel ring; towel bar; napkin ring; soap dish; soap holder; tumbler holder; toilet paper holder; robe hook; bathroom accessory; bathroom accessories; bathroom accessories set; curtain rod; curtain bracket; curtain rail; curtain track; curtain pipe; curtain rod bracket; curtain hook; curtain ring; curtain fitting; curtain pole; drape rod; mounting bracket
830242|Other mountings, fittings and similar articles suitable for furniture, of base metal|cabinet handle; furniture handle; drawer handle; wardrobe handle; knob; cabinet knob; drawer knob; profile handle; gola profile; g profile; j profile; telescopic channel; drawer channel; drawer slide; soft close channel; soft close drawer slide; ball bearing slide; slide; slides; sliding channel; tandem box; drawer system; hydraulic stay; gas spring; gas stay; lift up stay; aventos; cabinet leg; cabinet foot; furniture leg; sofa leg; table leg; adjustable leg; leveller; furniture foot; furniture fitting; wardrobe fitting; wardrobe rod; wardrobe lift; wardrobe accessory; pull out; pull out unit; bottle pull out; corner unit; magic corner; carousel; cabinet bracket; shelf support; shelf pin; furniture connector; cam lock connector; minifix; dowel; furniture screw cover; shelf bracket furniture; hanging rod; clothes rail; hanger rod; wardrobe pipe; trouser rack; tie rack; shoe rack fitting; basket fitting; cabinet organizer
830250|Hat-racks, hat-pegs, brackets and similar fixtures of base metal|bracket; wall hook; hat rack; coat hook; cloth hook; hook; hooks; hanger hook; coat hanger hook; robe hook; hat hook; clothes hook; hat peg; wall bracket small; shelf bracket small; hanging hook
830260|Automatic door closers of base metal|door closer; hydraulic door closer; automatic door closer; door closer 80 kg; floor hinge; floor spring door; door closer with hold open
8303|Armoured or reinforced safes, strong-boxes and doors and safe deposit lockers for strong-rooms, cash or deed boxes and the like, of base metal|safe; locker; safe locker; digital safe; strongbox; strong box; cash box; fire proof safe; fireproof safe; bank locker; home safe; hotel safe; laptop safe; wall safe; safe box; deposit locker; electronic safe; cash locker
8310|Sign-plates, name-plates, address-plates and similar plates, numbers, letters and other symbols, of base metal, excluding those of heading 9405|name plate; nameplate; name board; sign plate; address plate; house number plate; door name plate; metal letters; steel letters; ss letters; brass letters; metal number; metal numbers; ss name plate; brass name plate; steel name plate; metal sign; sign board metal; metal name board; steel signage; metal signage letters; stainless steel letters; aluminium letters sign; engraved plate; engraved name plate; etched plate; embossed plate; metal tag; name tag; tag; name tag metal; metal badge; badge; number plate; vehicle number plate; flat number plate; door number; room number plate; room sign; door sign; signage plate; plaque; commemorative plaque; brass plaque; ss plaque; metal plaque; display plate
8306|Bells, gongs and the like, non-electric, of base metal; statuettes and other ornaments, of base metal; photograph, picture or similar frames, of base metal; mirrors of base metal|metal statue; metal sculpture; metal ornament; brass statue; brass idol; metal idol; metal showpiece; metal decor; metal wall art decor; decorative metal item; metal bell; temple bell; door bell non electric; gong; brass bell; metal photo frame; metal frame photo; brass frame; metal mirror frame; steel photo frame; metal figurine; metal artefact; artefact; metal handicraft; handicraft; showpiece; metal wall hanging; wall hanging; metal tree; metal flower; metal decorative piece
9406|Prefabricated buildings|prefabricated building; prefab building; prefab house; prefab cabin; portable cabin; porta cabin; modular building; container office; container house; site office; labour shed; security cabin; guard cabin; guard room; toilet cabin; prefab toilet; modular toilet; prefab structure; pre fab; puf panel cabin; steel prefab; pre engineered building
# ---------------------------------------------------------------- Plumbing: taps, valves, showers
848180|Other appliances: taps, cocks, valves and similar appliances for pipes, boiler shells, tanks, vats or the like, including thermostatically controlled valves|tap; taps; faucet; bib cock; bibcock; mixer; mixer tap; basin mixer; shower mixer; diverter; angle cock; pillar cock; ball valve; gate valve; globe valve; valve; valves; foot valve; float valve; flush valve; sink mixer; wall mixer; cp fittings; cp fitting; chrome plated fitting; sanitary fittings; bathroom fittings; health faucet; jet spray; shower; overhead shower; hand shower; rain shower; shower head; shower arm; shower set; shower panel; brass valve; pvc valve; cpvc valve; ppr valve; butterfly valve; solenoid valve; water solenoid valve; sluice valve; plug valve; needle valve; stop cock; stopcock; wall tap; sink tap; basin tap; kitchen tap; long body tap; pillar tap; sensor tap; touchless tap; automatic tap; flush tank fitting; waste coupling; bottle trap; floor drain; floor trap; drain trap; floor drain cover; floor waste; shower drain; angle valve; concealed stop cock; concealed valve; flush plate; flush button; dual flush plate; flush valve toilet; flush tank valve
848130|Check (non-return) valves|check valve; non return valve; nrv; foot valve check; swing check valve; wafer check valve; reflux valve; one way valve
848140|Safety or relief valves|safety valve; relief valve; pressure relief valve; prv relief; pop safety valve; overflow valve; air release valve; vacuum breaker
848110|Pressure-reducing valves|pressure reducing valve; prv; pressure regulator valve; water pressure reducing valve; pressure control valve; pressure reducer; gas pressure regulator; water pressure regulator
# ---------------------------------------------------------------- Lighting fittings and signs (9405)
9405|Lamps and lighting fittings including searchlights and spotlights and parts thereof, not elsewhere specified or included; illuminated signs, illuminated name-plates and the like|light; lights; lighting; light fitting; lighting fitting; lamp; lamps; luminaire; light fixture; decorative light; decorative lighting; interior lighting; exterior lighting; architectural lighting; lighting fixture; lights fitting; light installation material
940511|Chandeliers and other electric ceiling or wall lighting fittings, designed for use solely with LED light sources|chandelier; led chandelier; ceiling light; led ceiling light; panel light; led panel light; downlight; down light; led downlight; recessed light; recessed downlight; ceiling lamp; surface panel light; surface light; surface mounted light; cob light; cob downlight; wall light; wall lamp; wall sconce; led wall light; sconce; pendant light; pendant lamp; hanging light; hanging lamp; hanging pendant; track light; track lights; rail light; magnetic track light; cove light; cove lighting; profile light; linear light; led linear light; led profile light; ceiling fixture; flush mount light; flush mount ceiling light; ceiling mounted light; ceiling lights; led ceiling panel; led round panel; led square panel; concealed light; concealed lighting; mood light; wall washer light; wall grazer; step light; stair light; niche light; louver light; grid light; trimless light; trimless downlight; pop light; pop downlight; false ceiling light; false ceiling lights; cabin light; led cabin light; strip ceiling light
940519|Other electric ceiling or wall lighting fittings|ceiling light non led; halogen ceiling light; fluorescent ceiling light; fluorescent fitting; tube light fitting; tube light fixture; batten fitting; cfl ceiling light; bulb holder ceiling; ceiling fan light; chandelier crystal; crystal chandelier; jhumar; jhoomer; glass chandelier
940521|Electric table, desk, bedside or floor-standing lamps, designed for use solely with LED light sources|table lamp; desk lamp; study lamp; bedside lamp; floor lamp; standing lamp; reading lamp; night lamp; led table lamp; led desk lamp; floor standing lamp; arc lamp floor; tripod lamp; led night lamp; touch lamp; study table lamp; rechargeable table lamp; bed lamp; side lamp; led floor lamp; lamp shade set; lampshade lamp; led table light; table light; desk light
940531|Christmas tree lighting sets and string lights, designed for use solely with LED light sources|fairy light; fairy lights; string light; string lights; led string lights; christmas lights; christmas light; decoration lights; decoration light; diwali lights; diwali light; serial light; serial lights; curtain lights; curtain light; rice lights; rice light; led rice light; icicle lights; net lights; festival lights; festival lighting; decorative string; led garland; led serial set; twinkle lights; lantern string lights; globe string lights; party lights; wedding lights; wedding lighting; outdoor string lights
940541|Photovoltaic electric lamps and lighting fittings, designed for use solely with LED light sources|solar light; solar street light; solar garden light; solar lamp; solar flood light; solar led light; solar bollard light; solar wall light; solar pole light; solar post light; solar fence light; solar path light; solar lantern; solar powered light; solar led street light; solar led flood light; solar security light; solar motion light; solar spike light; solar fairy lights; solar deck light; solar lawn light; solar high mast; solar led lamp; all in one solar light; integrated solar street light
940542|Other electric lamps and lighting fittings, designed for use solely with LED light sources|led light; led lights; led lighting; focus light; focus lights; spot light; spotlight; led spot light; led spotlight; track spot; lens light; flood light; led flood light; floodlight; street light; led street light; garden light; led garden light; bollard light; pole light; pole with light; light pole with fitting; post light; led batten; led tube fitting; bulkhead; bulkhead light; wall washer; facade light; facade lighting; underwater light; pool light; swimming pool light; high bay; low bay; led high bay; linear high bay; led luminaire; luminaire led; lighting fixture led; led fixture; led strip; strip light; led strip light; led tape; led tape light; rope light; cove strip; led neon flex; neon flex; led neon; flexible neon; led flexible strip; cob strip; cob led strip; led bar; led bar light; led line light; led wall washer; inground light; in ground light; uplight; up light; ground light; buried light; deck light; landscape light; landscape lighting; garden spike light; spike light; led gate light; gate light; compound wall light; boundary wall light; outdoor wall light; outdoor light; outdoor lighting; exterior wall light; led bulkhead; led canopy light; canopy light; petrol pump light; led tunnel light; tunnel light; led emergency light; emergency light; led mirror light; mirror light; picture light; led picture light; gallery light; showcase light; display light; cabinet light; wardrobe light; under cabinet light; under counter light; kitchen cabinet light; led sensor light; sensor light; motion sensor light; pir light; smart light; wifi light; wifi led light; rgb light; rgb led light; color changing light; colour changing light; dmx light; stage light; par light; led par; moving head; disco light; laser light; party light; led flood 50w; led flood 100w; led spot 12w; led spot 7w; led spot 3w
940549|Other electric lamps and lighting fittings|halogen light; halogen lamp; halogen spot; halogen flood; metal halide light; metal halide fitting; hid light; mercury vapour light; sodium vapour light; incandescent fitting; electric lantern; electric lamp fitting; lantern; garden lantern; outdoor lantern; wall lantern; decorative lamp; antique lamp; tiffany lamp; moroccan lamp; rattan lamp; bamboo lamp; cane lamp; lamp shade fitting; light shade; lamp shade; lampshade; shade; jute lamp; hanging basket light; glass pendant; brass pendant; designer pendant; designer light; designer lamp; designer lighting; decor light
940550|Non-electrical lamps and lighting fittings|oil lamp; kerosene lamp; lantern non electric; hurricane lamp; petromax; gas lamp; candle lamp; candle stand; candle holder; diya; diyas; earthen lamp; brass oil lamp; samai; vilakku; tealight holder; tea light holder; candle lantern; torch non electric
940561|Illuminated signs, illuminated name-plates and the like, designed for use solely with LED light sources|illuminated sign; led sign board; led signboard; sign board with light; lighted sign; glow sign; glow sign board; neon sign; led name plate; illuminated name plate; backlit sign; backlit signage; acrylic led sign; 3d led letters; led letters; channel letter; channel letters; led channel letter; lit signage; sign with light; light box; lightbox; led light box; name board led; lighted name plate; lighted nameplate; name tag light; name tag with light; name tag with lighting; led name board; led display board; led board sign; shop sign led; shop name board; hoarding light; hoarding; led hoarding; acrylic letters led; metal letters led; halo lit letters; backlit letters; illuminated letters; illuminated logo; led logo; logo sign; led logo sign; led box; led frame; led photo frame; backlit frame; backlit panel; backlit acrylic panel; led backlit panel; led signage; signage led; signage; sign board; signboard; sign boards; led glow sign; exit sign; led exit sign; emergency exit sign; exit board; illuminated exit sign
940569|Other illuminated signs, illuminated name-plates and the like|neon tube sign; neon light sign; neon signage; glass neon sign; neon letters; neon board; fluorescent sign; non led sign; bulb sign board; marquee letters; marquee sign; bulb letters
940591|Parts of lamps and lighting fittings, of glass|lamp glass; glass shade; light glass; glass lamp shade; lamp chimney; glass cover light; glass diffuser; glass globe; glass dome light
940592|Parts of lamps and lighting fittings, of plastics|light diffuser; plastic diffuser; diffuser; light cover; plastic light cover; lamp cover; led cover; plastic shade; light housing plastic; lamp housing; light holder plastic; lens; led lens; reflector; led reflector; light reflector plastic
940599|Other parts of lamps and lighting fittings|light parts; lamp parts; lighting parts; light holder; lamp holder fitting; light bracket; light mounting bracket; light housing; light body; light driver housing; light clip; spring clip light; downlight clip; trim ring; light trim; led housing; led downlight housing; downlight housing; downlight body; spot housing; spot light housing; spot holder; mr16 holder; gu10 holder; light mounting ring; mounting ring; light base; spot base; panel frame; panel light frame; light frame; light profile accessory; profile end cap; profile cover; profile diffuser; profile clip; profile connector; led profile connector; led profile accessories; aluminium profile cover; lamp post part; pole bracket; light pole arm; pole arm; pole fitting; pole top; pole base; pole base plate; foundation plate
`;
