// HSN codes: furniture, home furnishing and decor, frames, a few household appliances, tools, brushes and plants (what an interiors and fit-out business also sells).
// One line per code:  code|description|name; another name; ...      (4 digits = heading, 6 digits = sub-heading; a line that starts with # is a comment)

export const GOODS_GENERAL = `
# ---------------------------------------------------------------- Seats and furniture (9401, 9403), mattresses and cushions (9404)
9401|Seats (other than those of heading 9402), whether or not convertible into beds, and parts thereof|seat; seating; chair; chairs; sofa; stool; bench; furniture seating; seating furniture
940139|Swivel seats with variable height adjustment, of other materials|office chair; revolving chair; swivel chair; executive chair; ergonomic chair; computer chair; task chair; boss chair; mesh chair; manager chair; director chair; high back chair; low back chair; gaming chair; adjustable chair; chair with wheels; visitor chair swivel
940161|Other seats with wooden frames, upholstered|sofa; sofa set; couch; l shaped sofa; l shape sofa; 3 seater sofa; 2 seater sofa; 1 seater sofa; loveseat; sectional sofa; chesterfield sofa; recliner; recliner sofa; upholstered chair; upholstered bench; cushioned chair; dining chair upholstered; accent chair; lounge chair; armchair; arm chair; wing chair; bed bench; sofa chair; wooden sofa; fabric sofa; leather sofa; sofa cum bed; settee; diwan; wooden diwan; window seat; upholstered seat; upholstered stool; pouffe; ottoman; puffy
940169|Other seats with wooden frames|wooden chair; dining chair; wooden bench; wooden stool; teak chair; wooden armchair; garden chair wooden; wooden swing; jhula; swing; wooden swing chair; rocking chair; bar stool wooden; wooden bar chair; folding chair wooden; bench wooden; wooden seating
940171|Other seats with metal frames, upholstered|visitor chair; steel chair upholstered; cafeteria chair; waiting chair; waiting area chair; metal frame chair; chrome chair; reception chair; conference chair; bar stool; bar chair; high stool; counter stool; stool upholstered; metal sofa; steel frame sofa
940179|Other seats with metal frames|steel chair; metal chair; iron chair; ms chair; ss chair; folding chair; garden chair; outdoor chair; cafe chair; wrought iron chair; steel bench; metal bench; ms bench; park bench; waiting bench; airport chair; gang chair; steel stool; iron stool; metal stool
940180|Other seats|plastic chair; plastic stool; stackable chair; plastic armchair; fibre chair; fiber chair; molded chair; moulded chair; acrylic chair; resin chair; bean bag; beanbag; bean bag chair; kids chair; baby chair; school chair; study chair; chair kids
940310|Metal furniture of a kind used in offices|steel office furniture; metal filing cabinet; filing cabinet; steel filing cabinet; steel cupboard office; office steel rack; metal office table; steel table; office almirah; steel office cupboard; metal desk; steel desk; metal office cabinet; file cabinet; document cabinet; plan chest
940320|Other metal furniture|steel almirah; steel cupboard; godrej almirah; metal almirah; steel wardrobe; metal wardrobe; iron bed; metal bed; steel bed; steel rack; metal rack; iron rack; ms rack; storage rack; display rack; shoe rack metal; steel shoe rack; locker; steel locker; staff locker; metal locker; school locker; angle rack; slotted angle rack; shelving rack; pallet rack; supermarket rack; garment rack; clothes stand; metal shelf; steel shelf; wire shelf; metal table; iron table; ms table; steel stand furniture; metal stand; metal furniture; iron furniture; wrought iron furniture; metal bunk bed; wall mounted rack metal; kitchen rack steel; pantry rack
940330|Wooden furniture of a kind used in offices|office table; executive table; office desk; workstation; work station; modular workstation; reception counter; reception desk; office cabin; conference table; meeting table; boardroom table; cubicle; office cubicle; computer table; manager table; director table; cabin furniture; office cabinet; filing cabinet wooden; office storage; office furniture; wooden office table; l shaped table; l shape table; office partition table; training room table; discussion table; counter office; front desk; wooden reception; reception table; office credenza
940340|Wooden furniture of a kind used in the kitchen|modular kitchen; kitchen cabinet; kitchen unit; kitchen furniture; kitchen carcass; base unit; wall unit kitchen; tall unit kitchen; kitchen shutter; kitchen trolley wooden; pantry unit; crockery unit kitchen; kitchen storage unit; kitchen drawers; kitchen cabinets; kitchen cupboard; kitchen shelf; kitchen counter wooden; kitchen island; island unit; kitchen platform cabinet; plywood kitchen; wooden kitchen
940350|Wooden furniture of a kind used in the bedroom|bed; wooden bed; cot; double bed; single bed; king size bed; queen size bed; queen bed; king bed; bunk bed; kids bed; bed with storage; storage bed; wardrobe; wooden wardrobe; sliding wardrobe; hinged wardrobe; walk in wardrobe; walk in closet; dressing table; dresser; bedside table; night stand; nightstand; bedside cabinet; headboard; bed headboard; chest of drawers; bedroom furniture; bedroom set; wardrobe loft; loft; kids wardrobe; baby cot; crib; cradle; wooden cradle; almirah wooden; wooden almirah; cupboard wooden
940360|Other wooden furniture|sideboard; side board; sideboards; tv unit; tv cabinet; tv stand; television unit; entertainment unit; display unit; wall unit; bookshelf; book shelf; bookcase; shoe rack; shoe cabinet; shoe storage; console table; console; coffee table; centre table; center table; side table; end table; dining table; wooden table; study table; crockery unit; pooja unit; pooja mandir; mandir; temple unit; wooden mandir; bar unit; bar cabinet; wooden rack; shelf unit; wall shelf; wall shelves; floating shelf; shelf; shelves; cabinet; wooden cabinet; storage unit; storage cabinet; credenza; buffet; showcase; display cabinet; trophy cabinet; wooden partition; wooden screen; room divider; foldable screen; counter; wooden counter; table; tables; furniture; wooden furniture; teak furniture; wooden console; wooden stand; wooden stool table; plant stand; wooden plant stand; hall table; foyer unit; foyer table; entryway bench; study unit; study desk; kids study table; computer desk home; laptop table; bed side unit; wooden bench storage; chest; trunk wooden; wooden chest; dressing unit; vanity unit; vanity cabinet; bathroom cabinet; bathroom vanity; wash basin cabinet
940370|Furniture of plastics|plastic table; plastic cabinet; plastic shelf; plastic rack; plastic wardrobe; plastic furniture; plastic shoe rack; modular plastic furniture; plastic dining table; plastic drawer unit; plastic chest of drawers; plastic storage cabinet; plastic stand; fibre table; resin table; plastic side table
940389|Furniture of other materials, including cane, osier, bamboo or similar materials|glass table; glass furniture; cane furniture; bamboo furniture; rattan furniture; acrylic furniture; stone table; marble table; composite furniture; wpc furniture; glass top table; glass coffee table; glass console; mirror furniture; mirrored furniture; wicker furniture; cane chair table; cane sofa; cane basket furniture; marble top table; granite table; resin furniture
940399|Parts of furniture of other materials|furniture part; furniture parts; table top; table base; furniture panel; furniture component; table leg set; furniture frame; drawer front
9404|Mattress supports; articles of bedding and similar furnishing (for example, mattresses, quilts, eiderdowns, cushions, pouffes and pillows)|bedding; bedding set; bed set
940421|Mattresses of cellular rubber or plastics, whether or not covered|foam mattress; memory foam mattress; latex mattress; pu foam mattress; rubber foam mattress; mattress topper; foam sheet mattress; sleepwell mattress; kurlon mattress; gel mattress
940429|Mattresses of other materials|mattress; spring mattress; bonnell mattress; pocket spring mattress; coir mattress; bed mattress; single mattress; double mattress; king mattress; queen mattress; orthopaedic mattress; cotton mattress; gadda; hotel mattress; hospital mattress; kids mattress
940490|Other articles of bedding and similar furnishing: quilts, comforters, duvets, pillows, cushions|pillow; cushion; quilt; comforter; duvet; bolster; pillow cushion; sofa cushion; seat cushion; chair cushion; back cushion; floor cushion; decorative cushion; throw pillow; pillow insert; cushion insert; razai; rajai; bed quilt; sleeping bag
# ---------------------------------------------------------------- Soft furnishing: curtains, blinds, carpets, wallpaper, wall coverings
6303|Curtains (including drapes) and interior blinds; curtain or bed valances|curtain; curtains; drapes; drape; sheer curtain; blackout curtain; door curtain; window curtain; eyelet curtain; readymade curtain; curtain set; valance; curtain valance; roller blind; roller blinds; zebra blind; roman blind; blinds; blind; window blind; vertical blind; sheer blind; day night blind; honeycomb blind; wooden blind; bamboo blind; motorised blind; motorized blind; smart blind; motorised curtain; shades; window shade; roller shade; curtain with lining; velvet curtain; linen curtain; net curtain; lace curtain; shower curtain; curtain panel; curtain cloth stitched
6304|Other furnishing articles, excluding those of heading 9404 (bedspreads, cushion covers, sofa covers)|bedspread; bed cover; cushion cover; sofa cover; table runner; chair cover; furnishing article; sofa throw; throw; wall hanging fabric; tapestry; upholstery cover; bed runner; bed skirt; pillow cover decorative; mattress cover decorative; table mat fabric; placemat
6302|Bed linen, table linen, toilet linen and kitchen linen|bed sheet; bedsheet; bed linen; towel; bath towel; hand towel; table cloth; tablecloth; table linen; napkin; kitchen towel; pillow cover; pillow case; pillowcase; mattress protector; mattress cover; bath robe; face towel; hotel linen; hotel towel; bed sheets; duvet cover; quilt cover; comforter cover
6301|Blankets and travelling rugs|blanket; blankets; travelling rug; woollen blanket; fleece blanket; acrylic blanket; hospital blanket; relief blanket
5703|Carpets and other textile floor coverings, tufted, whether or not made up|carpet; carpets; carpet roll; wall to wall carpet; broadloom carpet; tufted carpet; nylon carpet; office carpet; carpet tile; carpet tiles; modular carpet; artificial grass; artificial turf; synthetic grass; turf; synthetic turf; grass carpet; rug tufted; hotel carpet; commercial carpet; printed carpet; event carpet; exhibition carpet; carpet flooring
5701|Carpets and other textile floor coverings, knotted, whether or not made up|hand knotted carpet; hand knotted rug; persian carpet; silk carpet; wool carpet hand knotted; kashmiri carpet; oriental rug
5702|Carpets and other textile floor coverings, woven, not tufted or flocked|dhurrie; durrie; kilim; woven carpet; woven rug; jute mat; jute rug; coir mat; coir matting; coir carpet; cotton rug; cotton dhurrie; flat weave rug; handloom rug; woven floor covering
5705|Other carpets and other textile floor coverings, whether or not made up|mat; door mat; floor mat; bath mat; rug; area rug; nonwoven carpet; non woven carpet; felt carpet; needle punch carpet; needle punch mat; exhibition mat; felt mat; yoga rug; anti skid mat; kitchen mat; entrance mat; welcome mat
4814|Wallpaper and similar wall coverings; window transparencies of paper|wallpaper; wall paper; wall covering paper; vinyl wallpaper; 3d wallpaper; wall mural; photo wallpaper; self adhesive wallpaper; peel and stick wallpaper; textured wallpaper; fabric wallpaper; designer wallpaper; non woven wallpaper; wallpaper roll; kids wallpaper; custom wallpaper; wall decal; wall sticker paper; mural wallpaper; wall coverings; wall covering
# ---------------------------------------------------------------- Decor: frames, art, ornaments, clocks, plants
4911|Other printed matter, including printed pictures and photographs|poster; wall poster; print; framed print; printed picture; wall art print; photographs print; calendar; brochure; catalogue; leaflet; flyer; pamphlet; printed matter; visiting card; business card; photo print; photograph; canvas print; printed canvas; digital print; poster print; wall print; sticker print; printed sticker; hanging calendar; table calendar; wall calendar; diary calendar; flex print; flex banner; vinyl print; vinyl banner; banner; standee; printed banner; sun board print; foam board print; flex board
4909|Printed or illustrated postcards; printed cards bearing personal greetings, messages or announcements|greeting card; invitation card; wedding card; postcard; birthday card; visiting cards; id card paper; announcement card
9701|Paintings, drawings and pastels, executed entirely by hand|oil painting; canvas painting; hand painted painting; art painting; artwork; abstract painting; acrylic painting art; wall painting art; portrait; canvas art; wall art painting; handmade painting; madhubani painting; tanjore painting; art piece; modern art painting; landscape painting; framed painting; mural art canvas; hand painted canvas; pencil art; sketch; charcoal drawing; hand drawn art
9703|Original sculptures and statuary, in any material|sculpture; statue; marble statue; stone statue; bronze statue; fibre statue; resin statue; fiberglass sculpture; stone sculpture; metal sculpture art; idol; marble idol; stone idol; wooden sculpture; art sculpture; statuary; garden statue; buddha statue; ganesha statue; fountain statue; life size statue; bust
6913|Statuettes and other ornamental ceramic articles|ceramic showpiece; ceramic vase; ceramic planter; ceramic pot; ceramic decor; porcelain figurine; ceramic statue; decorative ceramic; ceramic ornament; ceramic idol; ceramic flower pot; flower vase ceramic; ceramic figurine; ceramic sculpture; terracotta decor; terracotta showpiece; ceramic wall art; ceramic wall hanging; terracotta pot decorative; decorative pot; showpiece ceramic
6914|Other ceramic articles|ceramic article; terracotta pot; clay pot; earthen pot; matka; ceramic planter plain; earthen planter; clay planter; terracotta planter; flower pot; plant pot; garden pot; ceramic jar; ceramic container; ceramic tray; clay article; earthenware
6702|Artificial flowers, foliage and fruit and parts thereof; articles made of artificial flowers, foliage or fruit|artificial plant; artificial plants; artificial flower; artificial flowers; artificial tree; artificial foliage; artificial leaf; plant decor artificial; vertical garden artificial; green wall artificial; fake plant; faux plant; artificial grass wall; artificial hedge; artificial creeper; artificial garland; artificial bouquet; artificial fruit; artificial topiary; artificial ivy; artificial moss; preserved moss; moss wall; plastic plant; silk flower; artificial greenery; foliage panel
9105|Other clocks|wall clock; clock; table clock; alarm clock; digital clock; analog clock; pendulum clock; grandfather clock; desk clock; led clock; wall watch; designer wall clock; decorative clock; quartz clock; clocks; table top clock; cuckoo clock; flip clock
0602|Other live plants (including their roots), cuttings and slips; mushroom spawn|plant; plants; live plant; potted plant; indoor plant; indoor plants; outdoor plant; garden plant; sapling; tree sapling; ornamental plant; bonsai; money plant; snake plant; palm; palm tree; rose plant; flowering plant; foliage plant; shrub; shrubs; hedge plant; creeper; bamboo plant; succulent; cactus; natural plant; green plant; nursery plant; landscape plant
# ---------------------------------------------------------------- Household appliances and kitchen fittings not in the other tables
732111|Cooking appliances and plate warmers for gas fuel or for both gas and other fuels, of iron or steel|gas stove; gas cooktop; cooktop gas; gas hob; built in hob; hob; 2 burner gas stove; 3 burner gas stove; 4 burner hob; lpg stove; table top gas stove; cooking range; kitchen stove; glass top gas stove; burner; gas burner; gas stove 2 burner; gas stove 3 burner; gas stove 4 burner; gas stove 5 burner; built in gas hob; gas range; stainless steel gas stove
8450|Household or laundry-type washing machines, including machines which both wash and dry|washing machine; washer; washing machines; front load washing machine; top load washing machine; semi automatic washing machine; fully automatic washing machine; washer dryer; laundry machine; commercial washing machine; industrial washing machine; washing machine 7 kg; washing machine 8 kg; washing machine 6 kg
845011|Washing machines, fully automatic, of a dry linen capacity not exceeding 10 kg|fully automatic washing machine; front loading washing machine; front load; top loading automatic washing machine
845012|Other washing machines, with built-in centrifugal drier, of a dry linen capacity not exceeding 10 kg|semi automatic washing machine twin tub; twin tub washing machine; washing machine with dryer; spin washer
847960|Evaporative air coolers|air cooler; desert cooler; room cooler; evaporative cooler; personal cooler; tower cooler; window cooler; industrial air cooler; cooler; evaporative air cooler; ducted air cooler; air cooler with water tank; water air cooler
9021|Orthopaedic appliances, hearing aids, and other appliances worn or carried to compensate for a defect or disability|walker; walking stick; crutch; wheelchair accessory; hearing aid; orthopaedic support; knee brace; back support belt
# ---------------------------------------------------------------- Tools, abrasives and brushes
8205|Hand tools (including glaziers' diamonds) not elsewhere specified; blow lamps; vices, clamps; anvils; portable forges|hand tool; hand tools; tool kit; toolkit; tool set; hand tool kit; trowel; plastering trowel; putty knife; scraper; paint scraper; wall scraper; crowbar; pickaxe; bench vice; vice; clamp; g clamp; c clamp; glass cutter; tile cutter hand; tile cutter manual; construction tool; masonry tool; plumbing tool; carpentry tool; electrician tool kit
820520|Hammers and sledge hammers|hammer; claw hammer; mallet; sledge hammer; rubber mallet; ball peen hammer; club hammer; wooden mallet; brick hammer; hammers
820530|Planes, chisels, gouges and similar cutting tools for working wood|chisel; wood chisel; plane; hand plane; jack plane; gouge; carving tool; wood carving tool; cold chisel; flat chisel; chisel set
820540|Screwdrivers|screwdriver; screw driver; screwdriver set; screw driver set; precision screwdriver; phillips screwdriver; star screwdriver; flat screwdriver; tester screwdriver; ratchet screwdriver; screwdriver kit
8202|Hand saws; blades for saws of all kinds (including slitting, slotting or toothless saw blades)|hand saw; saw blade; wood saw; hacksaw; hack saw blade; circular saw blade; band saw blade; jigsaw blade; saw; pruning saw; tenon saw; panel saw; saw blades; cutting saw blade; tct blade; hole saw; cutting blade for saw; marble cutting blade; diamond blade; diamond cutting blade
8203|Files, rasps, pliers (including cutting pliers), pincers, tweezers, metal cutting shears, pipe-cutters, bolt croppers, perforating punches and similar hand tools|pliers; plier; cutting plier; combination plier; nose plier; wire cutter; wire stripper; bolt cutter; pipe cutter; tweezers; pincer; crimping tool; file; files; rasp; metal file; wood file; needle file; tin snips; side cutter; diagonal cutter; long nose plier; cable cutter; cable stripper; crimper; lug crimping tool
8204|Hand-operated spanners and wrenches (including torque meter wrenches); interchangeable spanner sockets|spanner; wrench; spanner set; ring spanner; socket set; adjustable spanner; pipe wrench; allen key; hex key; torque wrench; box spanner; socket wrench; combination spanner; double ended spanner; ratchet; ratchet spanner; stillson wrench; monkey wrench; open end spanner
8207|Interchangeable tools for hand tools, whether or not power-operated, or for machine tools (drilling, boring, milling, cutting)|drill bit; drill bits; masonry drill bit; hss drill bit; wood drill bit; core bit; screwdriver bit; driver bit; chisel bit; sds bit; router bit; milling cutter; tap and die; threading die; hole cutter; step drill; spade bit; forstner bit; glass drill bit; tile drill bit; diamond core bit; bit set; drill bit set
846721|Drills of all kinds, tools for working in the hand, with self-contained electric motor|drill machine; electric drill; hammer drill; rotary hammer; cordless drill; impact driver; electric screwdriver; cordless screwdriver; drill driver; power drill; hand drill; impact drill; cordless impact driver; battery drill; sds drill; demolition hammer; breaker machine; chipping gun electric
846722|Saws, tools for working in the hand, with self-contained electric motor|circular saw; jigsaw; jig saw; electric saw; chain saw electric; reciprocating saw; hand held circular saw; marble cutter machine; tile cutting machine; wall chaser; wall cutter; cut off machine; chop saw; mitre saw; table saw; band saw machine
846729|Other tools for working in the hand, with self-contained electric motor|angle grinder; grinder; bench grinder; planer; electric planer; router machine; wood router; sander; electric sander; orbital sander; belt sander; heat gun; power tool; rotary tool; engraver; polisher; electric polisher; buffing machine; die grinder; trimmer; laminate trimmer; nailer electric; electric nailer; staple gun electric; glue gun; hot glue gun; paint sprayer electric; spray gun electric; electric spray gun; mixer paddle machine; paint mixer; putty mixer; cement mixer small; concrete vibrator; needle vibrator; floor grinder; floor polisher machine; core cutting machine; cutting machine
846711|Tools for working in the hand, pneumatic, rotary type (including combined rotary-percussion)|pneumatic drill; air drill; air impact wrench; pneumatic wrench; air grinder; air tool; pneumatic tool; air hammer; air chisel; air ratchet
846719|Other tools for working in the hand, pneumatic|pneumatic nailer; air nailer; air stapler; pneumatic stapler; nail gun; staple gun pneumatic; brad nailer; pneumatic gun; air gun
6804|Millstones, grindstones, grinding wheels and the like, without frameworks, for grinding, sharpening, polishing, trueing or cutting|grinding wheel; cutting wheel; cutting disc; cut off wheel; grinding disc; diamond wheel; polishing wheel; grindstone; sharpening stone; whetstone; oil stone; abrasive wheel; flap wheel; thin cutting disc
6805|Natural or artificial abrasive powder or grain, on a base of textile material, of paper, of paperboard or of other materials|sand paper; sandpaper; emery paper; abrasive paper; polishing pad; sanding sheet; sanding disc; flap disc; emery cloth; abrasive cloth; abrasive sheet; waterproof sandpaper; sand paper roll; sanding belt; abrasive belt; sanding sponge; sanding block
960340|Paint, distemper, varnish or similar brushes (other than brushes of subheading 960330); paint pads and rollers|paint brush; paint roller; roller brush; roller cover; paint pad; distemper brush; wall brush; varnish brush; brush set paint; paint roller set; texture roller; foam roller; paint brushes; painting brush; painting roller; paint roller extension; roller extension pole; paint tray; painting tools; flat brush; sash brush; angular brush; artist brush; wall painting brush; whitewash brush
960310|Brooms and brushes consisting of twigs or other vegetable materials bound together, with or without handles|broom; jhadu; floor broom; grass broom; coconut broom; phool jhadu; soft broom; stick broom; coconut stick broom; garden broom
960390|Other brushes, brooms, mops, dusters, squeegees, brush heads (cleaning)|mop; dust brush; cleaning brush; toilet brush; scrub brush; wire brush; floor brush; plastic broom; wiper; floor wiper; squeegee; duster; feather duster; cleaning mop; mop set; bottle brush; hand brush; scrubbing brush; sweeping brush; glass wiper; car brush; carpet brush; dust pan set; dustpan; toilet cleaning brush; cleaning wiper; microfibre mop; spin mop; flat mop; bucket mop
# ---------------------------------------------------------------- Packaging and printing material
4819|Cartons, boxes, cases, bags and other packing containers, of paper, paperboard, cellulose wadding or webs of cellulose fibres|carton; corrugated box; packing box; cardboard box; carton box; paper bag; paper carry bag; shopping bag paper; gift box; gift boxes; packaging box; box packaging; mono carton; die cut box; corrugated carton; paper box; packing carton; printed carton; sweet box
3923|Articles for the conveyance or packing of goods, of plastics; stoppers, lids, caps and other closures, of plastics|polythene bag; plastic bag; carry bag; garbage bag; bubble wrap; stretch film; plastic container; plastic box; plastic crate; plastic can; plastic packaging; plastic jar; plastic bottle; plastic drum; bin liner; zip lock bag; plastic pouch; plastic wrapping; pe bag; hdpe bag; non woven bag; plastic cap; plastic lid; plastic closure; plastic carboy; plastic pallet; plastic can 20 litre; bottle cap; bubble bag; air bubble sheet; packing roll
`;
