// SAC codes (Services Accounting Codes, all 99xxxx) for the New Item form: the code, what it covers, and the names people give such a service.
// One line per code:  code|description|name; another name; ...      (a line that starts with # is a comment)
// The descriptions follow the official GST classification of services; the names are what an item is called on a quote. Add names freely, the first line that fits wins a tie.

export const SERVICES = `
# ---------------------------------------------------------------- Construction, installation and finishing (9954)
9954|Construction services|construction; construction work; civil work; building work; contract work; works contract; turnkey; turnkey project; site work
995411|Construction of single or multi dwelling and multi-storied residential buildings|house construction; villa construction; apartment construction; residential construction; bungalow construction; home construction; flat construction; building construction
995412|Construction of other residential buildings such as hostels and old age homes|hostel construction; old age home construction
995413|Construction of industrial buildings, workshops and storage buildings|factory construction; industrial construction; warehouse construction; shed construction; industrial shed; workshop construction; pre engineered building construction; peb construction; peb erection
995414|Construction of commercial buildings such as offices, malls, hotels and showrooms|commercial construction; office construction; mall construction; hotel construction; restaurant construction; showroom construction; shop construction; resort construction
995415|Construction of other non-residential buildings such as schools, hospitals and temples|school construction; hospital construction; temple construction; clinic construction; institutional building
995416|Construction of other buildings not elsewhere classified|other construction
995419|Repair, alteration, renovation or remodelling of buildings|renovation; remodelling; remodeling; building repair; refurbishment; restoration; building renovation; home renovation; office renovation; interior renovation; building maintenance; repair work; repairing work
995421|Construction of highways, streets, roads, railways, bridges and tunnels|road construction; highway construction; bridge construction; tunnel construction; flyover construction; paver road; concrete road; cc road; bt road; pavement work
995422|Construction of harbours, waterways, dams, water mains and irrigation works|dam construction; canal construction; irrigation work; irrigation project; waterworks; check dam; farm pond; pond construction; reservoir construction
995423|Long-distance pipelines, communication and power lines, pumping and transformer stations|pipeline laying; cable laying; transmission line; power line work; underground cable laying; substation work; sub station; substation construction; electrical infrastructure; ofc laying; optical fibre laying
995424|Local water and sewage pipelines, electricity and communication cables|water pipeline; sewage line; sewer line; drainage work; storm water drain; underground water line; pipe laying; water supply line; water supply work; irrigation pipeline; drip pipeline laying; underground pipeline; drain laying
995425|Construction of mines and industrial plants|plant construction; industrial plant; mine construction; process plant
995426|Construction of power plants and related infrastructure|power plant construction; solar plant construction; solar power plant; solar epc; epc; wind farm; solar park; solar farm; ground mounted solar; rooftop solar epc
995427|Construction of outdoor sport and recreation facilities|sports ground; stadium construction; playground; swimming pool construction; pool construction; jogging track; sports court; tennis court; basketball court; badminton court; artificial turf installation; garden construction
995428|Other civil engineering works|civil engineering; civil contract; retaining wall; compound wall; boundary wall; landscape construction; landscaping work
995429|Repair, alteration or renovation of civil engineering constructions|civil repair; road repair; bridge repair
995431|Demolition services|demolition; dismantling; building demolition; demolition work; breaking work
995432|Site formation and clearance, test drilling and trenches|site clearance; site preparation; site formation; land levelling; land grading; land development; plot development; trenching; digging; boring work
995433|Excavating and earthmoving services|excavation; earth work; earthwork; earth moving; earthmoving; jcb work; cutting and filling; soil filling; backfilling
995434|Water well drilling and septic system installation|borewell; bore well; borewell drilling; tube well; tubewell drilling; water well drilling; well drilling; septic tank installation; septic tank; soak pit; rainwater harvesting; recharge well
995435|Other site preparation services|site preparation work
995441|Installation, assembly and erection of prefabricated buildings|prefab erection; prefabricated building; prefab installation; portable cabin installation; porta cabin; container office installation; modular building installation; peb installation; steel building erection
995442|Installation, assembly and erection of other prefabricated structures|structure erection; shed erection; polyhouse installation; greenhouse installation; greenhouse erection; polyhouse erection; poly house; green house; net house; gazebo installation; pergola installation; canopy installation; truss erection; steel structure erection; fabrication and erection; structure installation; tensile structure; tent installation; stage erection
995443|Installation of street furniture such as bus shelters, benches and public toilets|bus shelter; bench installation; street furniture; bollard installation; public toilet installation
995444|Other assembly and erection services|assembly and erection; erection and commissioning; assembly
995451|Pile driving and foundation services|piling; pile driving; foundation work; pile foundation; bored piling; micro piling; foundation
995452|Building framing and roof framing services|framing; roof framing; steel framing; light gauge steel framing; lgsf; lgsf construction; roof truss; truss work; stud framing; roof structure
995453|Roofing and waterproofing services|roofing; roof work; roofing work; roof sheeting; roof installation; metal roofing; waterproofing; water proofing; waterproofing work; terrace waterproofing; roof waterproofing; basement waterproofing; bathroom waterproofing; leakage repair; leak proofing; damp proofing; chemical treatment; injection grouting; pu waterproofing; membrane waterproofing; roof leak; terrace treatment
995454|Concrete services|concrete work; concreting; rcc; rcc work; pcc; shuttering; formwork; centering; shuttering work; slab casting; concrete laying; floor concrete; screeding; screed; stamped concrete; polished concrete; concrete finishing
995455|Structural steel erection services|steel erection; structural steel erection; steel structure; steel structure work; structural work; steel truss; ms structure; girder erection
995456|Masonry services|masonry; brick work; brickwork; block work; blockwork; stone masonry; stone work; stone laying; stone cladding work; stone cladding installation; wall construction; brick laying; aac block work; fly ash brick work
995457|Scaffolding services|scaffolding; scaffold; scaffolding work; cuplock scaffolding
995458|Other special trade construction services|special trade; chemical anchoring; core cutting; wall cutting; slab cutting; diamond cutting; concrete cutting; grouting; anchor fastening
995461|Electrical installation services including wiring, fire alarm and burglar alarm installation|electrical work; electrical installation; electrical wiring; wiring work; wiring; house wiring; concealed wiring; cabling; cable installation; electrification; panel installation; db installation; switchboard installation; fire alarm installation; burglar alarm installation; alarm installation; cctv installation; cctv camera installation; camera installation; security system installation; access control installation; intercom installation; video door phone installation; home automation installation; smart home installation; automation installation; automation work; smart switch installation; light fitting installation; lighting installation; led installation; fan installation; earthing; earthing work; lightning arrestor installation; lightning protection; solar installation; solar panel installation; solar system installation; rooftop solar installation; inverter installation; ups installation; generator installation; transformer installation; network cabling; structured cabling; lan cabling; lan installation; data cabling; fibre installation; electrical fitting; panel wiring; control panel wiring; electrical commissioning; sensor installation; knx installation; automation wiring; smart home wiring
995462|Water plumbing and drain laying services|plumbing; plumbing work; plumber; water plumbing; drain laying; drainage; sanitary work; sanitary installation; sanitary fitting; pipe fitting; pipe work; piping; piping work; water line; water supply installation; cp fitting; tap installation; bathroom fitting; toilet installation; wc installation; sewage work; hot water line; cpvc piping; ppr piping; pump installation; water tank installation; overhead tank installation; irrigation installation; drip irrigation installation; drip installation; sprinkler installation; irrigation system installation; rain water pipe; fire fighting piping; fire hydrant installation
995463|Heating, ventilation and air conditioning equipment installation services|hvac; hvac installation; ac installation; air conditioner installation; ac fitting; split ac installation; vrf installation; chiller installation; ventilation; ducting; duct work; ductwork; exhaust installation; cold room installation; cold storage installation; ahu installation; heat pump installation; solar water heater installation; geyser installation; water heater installation; ventilation system; air conditioning; ac work; refrigeration installation; chimney installation
995464|Gas fitting installation services|gas fitting; gas pipeline installation; lpg pipeline; gas line; png installation; gas piping; medical gas pipeline; gas connection
995465|Insulation services|insulation; insulation work; thermal insulation; acoustic insulation; sound insulation; acoustic treatment; heat insulation; roof insulation; pipe insulation; duct insulation; puf insulation; glass wool insulation; rockwool insulation; soundproofing; sound proofing; spray foam insulation; xps insulation
995466|Lift and escalator installation services|lift installation; elevator installation; lift erection; escalator installation; lift work; elevator erection; home lift installation; passenger lift installation; goods lift installation; dumbwaiter installation; stair lift installation; platform lift installation; lift fitting; lift commissioning
995468|Other installation services|installation; installation work; installation charges; installation charge; installation service; fitting; fitting work; fixing; fixing work; fitting and fixing; fixing charges; mounting; mounting work; erection; commissioning; testing and commissioning; installation and commissioning; site installation; on site installation; equipment installation; setup; setting up; wall mounting; tv mounting; tv installation; curtain motor installation; automatic gate installation; gate automation installation; boom barrier installation; rolling shutter installation; shutter installation; sliding gate installation; swing gate installation; automatic door installation; door installation; window installation; aluminium window installation; upvc window installation; glass partition installation; partition installation; modular kitchen installation; furniture installation; wardrobe installation; kitchen installation
995469|Repair, alteration or maintenance of installations|installation repair; installation maintenance; installation modification
995471|Glazing services|glazing; glass installation; glass fitting; glass work; glass fixing; glass door installation; structural glazing; curtain wall; curtain wall glazing; curtain wall installation; spider glazing; point fixed glazing; glass facade; glass railing; toughened glass fixing; window glazing; glass cladding; glass canopy; skylight glazing; glass roof
995472|Plastering services|plastering; plaster work; cement plaster; wall plaster; pop work; pop punning; punning; gypsum plaster; putty work; wall putty; wall finishing; sponge finish; texture plaster; rendering; external plaster; internal plaster; skim coat
995473|Painting services|painting; paint work; painting work; wall painting; interior painting; exterior painting; house painting; building painting; painting service; painting contractor; ceiling painting; texture painting; texture paint work; epoxy painting; epoxy coating work; spray painting; duco painting; polish work; pu polish; melamine polish; polishing work; wood polish; varnish work; enamel painting; waterproof paint work; distemper work; emulsion painting; putty and paint; primer coat; paint application; coating work; whitewash; white washing; limewash; colour wash; mural painting; stencil painting; lacquer painting; metal painting; grill painting; gate painting; steel painting; anti corrosive painting; industrial painting; floor painting; line marking; road marking; parking marking; floor marking; painting labour; paint labour; painter labour; painting charges; painting contractor work; labour for painting; paint labour charges; painter charges
995474|Floor and wall tiling services|tiling; tile work; tile laying; tile fixing; tile installation; floor tiling; wall tiling; flooring work; marble laying; granite laying; marble work; granite work; stone flooring; marble flooring; tile fitting; kota stone work; stone fixing; mosaic work; terrazzo flooring; floor laying; paver block laying; paving; cobble stone laying; tile grouting; ceramic tile work; tile cutting; floor polishing; marble polishing; marble polish; granite polish; floor grinding; floor finishing
995475|Other floor laying, wall covering and wall papering services|wallpaper installation; wall paper; wallpaper fixing; wall paper work; wall covering; wall panelling; wall paneling; pvc panel installation; wall panel installation; vinyl flooring; vinyl flooring installation; laminate flooring; wooden flooring; wooden flooring installation; carpet laying; carpet installation; carpet fitting; epoxy flooring; epoxy floor; pu flooring; rubber flooring; artificial turf; synthetic turf installation; grass carpet; sports flooring; floor covering; acoustic wall; wall cladding; fluted panel; 3d wall panel; wall decor; texture wall
995476|Joinery and carpentry services|carpentry; carpentry work; carpenter; joinery; joinery work; woodwork; wood work; wooden work; furniture making; modular kitchen work; wardrobe work; wooden panelling; door fitting; window fitting; shelving; cabinet work; loft work; custom furniture; furniture work; interior work; interior fit out; interior fitout; fit out; fitout; interior execution; interior contract; interior decoration work; shutter work; pvc shutter work; pvc shutter; pvc door work; pvc window work; window shutter work; door work; window work; upvc work; pvc work; frame work; door frame work; pvc door fixing; shutter fixing
995477|Fencing and railing services|fencing; fence installation; fencing work; railing; railing work; handrail; hand rail; staircase railing; balcony railing; glass railing installation; grill work; grill installation; gate work; gate installation; gate fabrication; barbed wire fencing; chain link fencing; compound fencing; solar fencing
995478|Other building completion and finishing services|false ceiling; false ceiling work; gypsum ceiling; pop ceiling; ceiling work; grid ceiling; gypsum board work; partition work; drywall; gypsum partition; cement board partition; cladding work; facade work; facade installation; elevation work; elevation cladding; facade cladding; acp cladding; acp installation; hpl cladding; terracotta cladding; composite panel installation; aluminium composite panel work; external cladding; louvers installation; finishing work; finishing; building finishing; completion work; handover work
995479|Repair, alteration or maintenance of completion and finishing works|finishing repair; repair of finishing work

# ---------------------------------------------------------------- Maintenance, repair and installation of goods (9987)
9987|Maintenance, repair and installation services (except construction)|amc; annual maintenance contract; annual maintenance; maintenance contract; service contract; preventive maintenance; breakdown maintenance; maintenance; maintenance service; repair; repair service; repairing; servicing; service and repair; comprehensive maintenance; amc charges; amc contract; amc service; amc services; repair and maintenance; repair maintenance; maintenance charges; repair charges; maintenance work; maintenance and repair; service charges amc
998711|Maintenance and repair of fabricated metal products, except machinery|metal repair; fabrication repair; welding repair
998712|Maintenance and repair of office and accounting machinery|office machine repair; printer repair; photocopier service; photocopier amc; xerox machine service; copier service; printer service; printer amc; printer maintenance; note counting machine repair
998713|Maintenance and repair of computers and peripheral equipment|computer repair; laptop repair; computer amc; computer maintenance; pc repair; it hardware maintenance; server maintenance; network equipment repair; desktop repair; laptop service; hardware support
998714|Maintenance and repair of transport machinery and equipment|vehicle repair; car repair; bike repair; vehicle service; vehicle servicing; vehicle maintenance; tractor repair; tractor service; tyre repair; denting painting
998715|Maintenance and repair of electrical household appliances|ac repair; ac service; ac servicing; ac amc; ac maintenance; air conditioner service; fridge repair; refrigerator repair; washing machine repair; appliance repair; home appliance repair; geyser repair; fan repair; tv repair; water purifier service; ro service; ro amc; water purifier amc; mixer repair; microwave repair; inverter repair; ups repair; battery repair
998716|Maintenance and repair of telecommunication equipment and apparatus|cctv amc; cctv maintenance; cctv repair; cctv service; camera repair; intercom repair; telephone repair; mobile repair; phone repair; network amc; telecom equipment repair; pbx repair; alarm system amc; security system amc; access control amc; security system maintenance; fire alarm amc; fire alarm maintenance; home automation amc; automation amc; automation maintenance; smart home maintenance
998717|Maintenance and repair of commercial and industrial machinery|machine repair; machinery repair; machinery maintenance; machine maintenance; industrial machinery amc; plant maintenance; pump repair; pump service; motor repair; motor rewinding; motor winding; generator service; generator amc; dg set amc; genset maintenance; compressor service; compressor repair; panel maintenance; electrical maintenance; electrical amc; transformer maintenance; boiler maintenance; hvac maintenance; hvac amc; ac plant maintenance; chiller maintenance; machine servicing; pump amc; borewell pump repair; irrigation system maintenance; drip system maintenance; plc servicing; scada maintenance; solar maintenance; solar panel cleaning and maintenance; solar amc
998718|Maintenance and repair of elevators and escalators|lift amc; lift maintenance; lift repair; lift servicing; elevator amc; elevator maintenance; escalator maintenance; elevator repair
998719|Maintenance and repair of other machinery and equipment|equipment repair; equipment maintenance; equipment servicing; other repair
998721|Repair of footwear and leather goods|shoe repair; bag repair; leather repair
998722|Repair of watches, clocks and jewellery|watch repair; clock repair; jewellery repair
998723|Repair of garments and household textiles|garment repair; alteration; tailoring repair; curtain repair
998724|Repair of furniture|furniture repair; furniture polish; sofa repair; sofa re-upholstery; upholstery repair; chair repair; furniture refurbishment; furniture servicing
998725|Repair of bicycles|bicycle repair; cycle repair
998726|Maintenance and repair of musical instruments|musical instrument repair
998727|Repair of photographic equipment and cameras|camera repair photographic
998729|Maintenance and repair of other goods|repair of other goods; general repair; minor repair
998731|Installation of fabricated metal products, except machinery|metal product installation
998732|Installation of industrial, manufacturing and service industry machinery and equipment|machine installation; machinery installation; plant installation; equipment installation machinery; installation of machinery; installation and commissioning of machine; industrial equipment installation; pump set installation; compressor installation; boiler installation; production line installation; conveyor installation; automation machinery installation; plc installation; scada installation; industrial automation installation
998733|Installation of office and accounting machinery and computers|computer installation; pc installation; printer installation; server installation; office machine installation; software installation; os installation; network setup; it setup; workstation installation
998734|Installation of radio, television and communications equipment and apparatus|tv installation service; dth installation; antenna installation; dish installation; satellite dish installation; wifi installation; router installation; network device installation; communication equipment installation; audio system installation; av installation; sound system installation; home theatre installation; projector installation; pa system installation; intercom system installation
998735|Installation of professional medical machinery, precision and optical instruments|medical equipment installation; instrument installation; precision instrument installation
998736|Installation of electrical machinery and apparatus|electrical equipment installation; electrical apparatus installation; electrical machine installation
998739|Installation of other goods|installation of other goods

# ---------------------------------------------------------------- Professional, technical and business services (9983)
9983|Other professional, technical and business services|professional services; technical services; consulting; consultancy; consultation; advisory
998311|Management consulting and management services|management consulting; management consultancy; strategy consulting; business strategy; hr consulting; operations consulting; supply chain consulting; marketing consulting
998312|Business consulting services including public relations|business consulting; business consultancy; business advisory; public relations; pr services; pr agency; consulting charges; consultation charges; consultancy charges; consultant fee; advisory fee
998313|Information technology (IT) consulting and support services|it consulting; it support; technical support; helpdesk; help desk; remote support; network support; it services; it consultancy; software support; support services; online support; customer support; it amc; it maintenance; software maintenance; technical assistance; troubleshooting; cloud consulting; erp support; crm support
998314|Information technology (IT) design and development services|software development; app development; mobile app development; web development; website development; website design; web design; software design; custom software; application development; erp development; erp implementation; crm development; crm implementation; crm customisation; crm customization; software customisation; api development; iot development; iot software; firmware development; plc programming; programming; coding; software engineering; ui ux design; ui design; ux design; ecommerce website; web application; saas development; dashboard development; automation software; scada development; hmi programming; app design; software configuration; system configuration; configuration; system integration
998315|Hosting and IT infrastructure provisioning services|hosting; web hosting; server hosting; cloud hosting; cloud server; domain; domain registration; data centre; data center; colocation; vps; saas subscription; server rental; cloud services; storage hosting; cloud subscription; software subscription; hosting charges
998316|IT infrastructure and network management services|network management; server management; it infrastructure management; managed services; infrastructure management; network monitoring; network administration; system administration; it infrastructure; managed it services
998319|Other information technology services|other it services; data entry; data processing; data migration; data backup; cyber security; cybersecurity; security audit; penetration testing; vapt; digital services
998321|Architectural advisory services|architectural consulting; architect consultation; architectural advice
998322|Architectural services for residential building projects|architect; architectural design; architectural services; house design; home design; villa design; residential design; residential architecture; floor plan; plan drawing; building plan; layout plan; elevation design; 2d drawing; working drawing; architectural drawing; drawings
998323|Architectural services for non-residential building projects|commercial design; commercial architecture; office design; showroom design; hotel design; industrial design building; facade design; elevation design commercial; non residential architecture
998324|Historical restoration architectural services|restoration architecture; heritage restoration; conservation architecture
998325|Urban planning services|urban planning; town planning; city planning; master planning urban
998326|Rural land planning services|land planning; rural planning; layout planning; land use planning
998327|Project site master planning services|site master planning; master plan; site planning; layout design
998328|Landscape architectural and advisory services|landscape design; landscape architect; landscape architecture; landscape consultancy; garden design; landscape planning
998331|Engineering advisory services|engineering consulting; engineering consultancy; engineering advice; technical consultancy; technical advisory; design consultancy
998332|Engineering services for building projects|structural design; structural engineering; structural drawing; structural consultancy; structural analysis; mep design; mep services; electrical design; plumbing design; hvac design; building services design; shop drawing; shop drawings; detailing; fabrication drawing; facade engineering; building engineering; civil design; rcc design; structural stability certificate; engineering design; design engineering; engineering services
998333|Engineering services for industrial and manufacturing projects|industrial engineering; process engineering; plant engineering; plant design; factory design; machine design; automation design; automation engineering; system design; control system design; panel design; industrial automation engineering
998334|Engineering services for transportation projects|road design; transportation engineering; traffic engineering
998335|Engineering services for power projects|power engineering; electrical engineering; power system design; solar design; solar engineering; solar plant design; energy audit; electrical audit; load calculation; electrical design consultancy
998336|Engineering services for telecommunications and broadcasting projects|telecom engineering; network design; broadcasting engineering; radio engineering
998337|Engineering services for waste management, water, sewerage and drainage projects|water engineering; sewerage design; drainage design; stp design; etp design; water treatment design; irrigation design; irrigation planning; drip design; waste management design
998338|Engineering services for other projects|engineering other; mechanical design; mechanical engineering
998339|Project management services for construction projects|project management; construction management; site supervision; project supervision; supervision; pmc; project management consultancy; site engineer; site management; quantity surveying; estimation; boq preparation; project monitoring; project coordination; site coordination; execution supervision
998341|Geological and geophysical consulting services|geological survey; geophysical survey; geology consulting
998342|Subsurface surveying services|subsurface survey; soil investigation; geotechnical investigation; soil testing survey; geotechnical survey
998343|Mineral exploration and evaluation|mineral exploration
998344|Surface surveying and map-making services|survey; land survey; site survey; topographical survey; topo survey; total station survey; drone survey; mapping; gis mapping; map making; dgps survey; contour survey; boundary survey; site measurement; site visit; measurement
998345|Weather forecasting and meteorological services|weather forecasting; weather service; meteorological service
998346|Technical testing and analysis services|testing; lab testing; soil testing; water testing; material testing; quality testing; testing charges; inspection; third party inspection; load testing; nde testing; ndt; calibration; calibration service; thermal imaging; energy audit testing; analysis; sample analysis; test report; site inspection; technical audit; quality audit
998347|Certification of ships, aircraft, dams and the like|certification; structural certification; stability certification; safety certification; iso certification audit
998348|Certification and authentication of works of art|art certification; art authentication; art valuation
998349|Other technical and scientific services|technical services other; scientific services; r and d service; crop advisory; agronomy advice; agri consulting; agricultural consulting; farm consulting; farm advisory; soil health advisory; precision farming service; agri advisory; technical consultation; feasibility study; feasibility report; project report; dpr; detailed project report; research study
998351|Veterinary services for pet animals|vet services; pet care; veterinary pets
998352|Veterinary services for livestock|livestock veterinary; cattle vet; animal health service
998359|Other veterinary services|veterinary services
998361|Advertising services|advertising; advertisement; ad campaign; digital marketing; online marketing; seo; search engine optimisation; social media marketing; social media management; social media; branding; brand promotion campaign; promotion; promotional services; marketing; marketing services; google ads; facebook ads; ad management; content marketing; email marketing; influencer marketing; hoarding advertising; outdoor advertising; flex advertising; lead generation; performance marketing
998362|Purchase or sale of advertising space or time on commission|advertising commission; media buying
998363|Sale of advertising space in print media|print advertisement; newspaper advertisement; magazine advertisement; classified ad
998364|Sale of TV and radio advertising time|tv advertisement; radio advertisement; tv ad; radio ad; fm ad
998365|Sale of Internet advertising space|internet advertising; banner advertisement; online advertisement; display advertising; website advertising space; sponsored post
998366|Sale of other advertising space or time|other advertising; billboard space; hoarding space; digital screen advertising; mall advertising; transit advertising
998371|Market research services|market research; market survey; survey services; customer survey; product research; competitor analysis; data collection survey; research services
998372|Public opinion polling services|opinion poll; public opinion; polling
998381|Portrait photography services|portrait photography; portrait photo; studio photography; passport photo; id photo
998382|Advertising and related photography services|product photography; advertising photography; catalogue photography; commercial photography; e commerce photography; product shoot; interior photography; architectural photography; real estate photography; photo shoot
998383|Event photography and event videography services|event photography; event videography; wedding photography; wedding videography; videography; video shooting; video shoot; photography; photographer; photo and video; cinematography; candid photography; drone photography; drone videography; aerial photography; aerial videography; drone shoot; video coverage; live streaming; live stream; event coverage
998384|Specialty photography services|specialty photography; aerial photography specialty; underwater photography; macro photography; 360 photography; virtual tour photography; 360 virtual tour
998385|Restoration and retouching services of photography|photo editing; photo retouching; photo restoration; image editing; image retouching
998386|Photographic and videographic processing services|photo processing; video processing; film processing; photo printing; album making; photo album
998387|Other photography and videography services|other photography; photo services; video services
998391|Specialty design services including interior design, fashion design and industrial design|interior design; interior designing; interior designer; interior design services; interior designing services; interior decoration; interior decorating; interior styling; interior consultation; interior consultancy; interior planning; space planning; design services; design service; design charges; design fee; designing; graphic design; logo design; brand design; brand identity; branding design; brochure design; packaging design; product design; industrial design; fashion design; furniture design; kitchen design; modular kitchen design; wardrobe design; lighting design; light design; color consultation; colour consultation; 3d design; 3d rendering; 3d visualisation; 3d visualization; 3d modelling; 3d modeling; 3d walkthrough; walkthrough; render; rendering design; concept design; mood board; design concept; design drawing; design consultation; vastu consultation; styling; exhibition design; stall design; booth design; set design; decor design; design and consultancy; design and supervision
998392|Design originals|design original; original design; pattern design; artwork; original artwork; textile design
998393|Scientific and technical consulting services|technical consulting; scientific consulting; scientific consultancy; expert consultation; expert services; technical expert; domain expert
998394|Original compilations of facts and information|database compilation; data compilation; research compilation; directory compilation
998395|Translation and interpretation services|translation; interpretation; translator; language services; document translation; transcription
998396|Trademarks and franchises|trademark; franchise; franchising; franchise fee; brand licence; brand license; trademark registration; trademark charges; royalty
998397|Sponsorship services and brand promotion services|sponsorship; brand promotion; brand ambassador; event sponsorship
998399|Other professional, technical and business services not elsewhere classified|other professional services; professional charges; professional fee; service charges; other services; miscellaneous services; misc services; liaison; liaison services; documentation; documentation charges; approval charges; permit; permit charges; statutory approvals; coordination

# ---------------------------------------------------------------- Legal and accounting (9982)
998211|Legal advisory and representation services concerning criminal law|criminal lawyer; criminal law
998212|Legal advisory and representation services concerning other fields of law|legal services; legal advice; legal consultation; advocate; lawyer; legal fees; legal charges; legal opinion; litigation; court representation; legal representation
998213|Legal documentation and certification concerning patents, copyrights and other intellectual property rights|patent filing; copyright registration; ip filing; patent attorney; design registration
998214|Legal documentation and certification concerning other documents|legal documentation; agreement drafting; drafting; deed drafting; notary; notarisation; contract drafting; agreement; legal notice; affidavit; stamp paper; document drafting; mou drafting; registration documentation
998215|Arbitration and conciliation services|arbitration; conciliation; mediation
998216|Other legal services|other legal services
998221|Financial auditing services|audit; auditing; statutory audit; internal audit; tax audit; gst audit; financial audit; audit fee; audit fees; audit services; audit charges; audit remuneration; auditor fees; auditor remuneration
998222|Accounting and bookkeeping services|accounting; bookkeeping; book keeping; accounts; accounting services; accounting charges; tally work; accounts writing; gst filing; gst return; return filing; gst compliance; roc filing; roc compliance; company compliance; compliance services; tds return; income tax return filing
998223|Payroll services|payroll; payroll processing; salary processing; payroll management
998224|Other accounting and related services|other accounting services
998231|Corporate tax consulting and preparation services|corporate tax; tax consulting; tax consultancy; tax planning; tax advisory; gst consulting; gst consultancy; gst advisory; income tax consulting
998232|Individual tax preparation and planning services|individual tax; personal tax; itr filing; income tax return individual
998240|Insolvency and receivership services|insolvency; receivership; liquidation services

# ---------------------------------------------------------------- Support services: staffing, security, cleaning, events (9985)
9985|Support services|support services; office support; support
998511|Executive search services|executive search; headhunting; head hunting
998512|Permanent placement services|recruitment; placement; permanent placement; recruitment services; hiring services; manpower recruitment; placement fee; recruitment fee
998513|Contract staffing services|contract staffing; staffing services; contract manpower; contract labour; outsourced staff
998514|Temporary staffing services|temporary staffing; temporary manpower; temp staff; temporary workers
998515|Long-term staffing (pay rolling) services|pay rolling; payrolling; third party payroll; long term staffing
998519|Other employment and labour supply services|labour supply; manpower supply; labour charges; labour contractor; labour; manpower; skilled manpower; unskilled labour; skilled labour; technician supply; workers supply; helper supply; labour work; labour contract; labor; labor charges; skilled workers; supply of manpower; supply of labour; worker charges; technician charges
998521|Investigation services|investigation; detective; private investigation; background verification
998522|Security consulting services|security consulting; security consultancy; security audit service
998523|Security systems services|security system service; cctv monitoring; alarm monitoring; remote monitoring; security monitoring; surveillance monitoring; video surveillance service; security system monitoring; monitoring service; monitoring charges
998524|Armoured car services|armoured car; cash van; cash in transit; cit services
998525|Guard services|security guard; security guards; guard service; security service; security services; watchman; security personnel; bouncers; guard charges; security agency
998526|Training of guard dogs|dog training; guard dog training
998527|Polygraph services|polygraph; lie detector test
998528|Fingerprinting services|fingerprinting; fingerprint service
998529|Other security services|other security services
998531|Disinfecting and exterminating services|pest control; disinfection; fumigation; sanitisation; sanitization; termite control; anti termite treatment; anti termite; pest management; rodent control; cockroach control; mosquito control; fogging; disinfecting; sanitising; deep sanitisation
998532|Window cleaning services|window cleaning; glass cleaning; facade cleaning glass; glass facade cleaning; window washing
998533|General cleaning services|cleaning; cleaning service; cleaning services; housekeeping; housekeeping services; deep cleaning; office cleaning; house cleaning; floor cleaning; janitorial; cleaning charges; post construction cleaning; final cleaning; carpet cleaning; sofa cleaning; sofa cleaning service; mechanised cleaning
998534|Specialised cleaning services for reservoirs and tanks|tank cleaning; water tank cleaning; reservoir cleaning; sump cleaning; overhead tank cleaning
998535|Sterilisation of objects or premises|sterilisation; sterilization; operation theatre sterilisation
998536|Furnace and chimney cleaning services|chimney cleaning; furnace cleaning; duct cleaning; kitchen exhaust cleaning
998537|Exterior cleaning of buildings|exterior cleaning; facade cleaning; building cleaning exterior; pressure washing; high pressure cleaning; building wash; elevation cleaning; solar panel cleaning
998538|Cleaning of transportation equipment|vehicle cleaning; car wash; car washing; bus cleaning; truck cleaning; vehicle washing
998539|Other cleaning services|other cleaning
998540|Packaging services of goods for others|packaging service; packing service; packing charges; packaging charges; packing and forwarding; packing and forwarding charges; pf charges; p and f charges; packing; packaging
998541|Parcel packing and gift wrapping|parcel packing; gift wrapping
998542|Coin and currency packing services|coin packing; currency packing
998549|Other packaging services|other packaging services
998551|Reservation services for transportation|ticket booking; flight booking; train booking; bus booking; travel booking; air ticket; transport reservation
998552|Reservation services for accommodation, cruises and package tours|hotel booking; accommodation booking; room booking; package tour booking; cruise booking
998553|Reservation services for convention centres, congress centres and exhibition halls|venue booking; hall booking; convention centre booking; exhibition hall booking
998554|Reservation services for event tickets and entertainment|event ticket booking; ticket booking events; cinema booking
998555|Tour operator services|tour operator; tour package; tours; travel agent; travel agency; tour services; holiday package
998556|Tourist guide services|tourist guide; guide services
998557|Tourism promotion and visitor information services|tourism promotion; tourist information
998559|Other travel arrangement and related services|travel arrangement; visa services; visa assistance; travel services; travel assistance
998591|Credit reporting and rating services|credit reporting; credit rating; credit report
998592|Collection agency services|collection agency; recovery services; debt collection; collection services
998593|Telephone-based support services|call centre; call center; telecalling; tele calling; telemarketing; bpo; customer care; customer service; inbound calls; outbound calls; telephone support
998594|Combined office administrative services|office administration; admin services; administrative support; back office; back office services; office management; front office
998595|Specialised office support services such as duplicating, mailing and document preparation|photocopying; xerox; photocopy; scanning; document scanning; digitisation; digitization; document preparation; typing; typing services; data typing; binding; lamination; laminating; spiral binding; mailing services; duplicating
998596|Events, exhibitions, conventions and trade shows organisation and assistance services|event management; event planning; event organising; event organizing; event organisation; events; exhibition; exhibition management; exhibition stall; exhibition services; trade show; trade fair; conference management; conference; seminar; seminar management; wedding planning; wedding planner; party planning; stage setup; stage decoration; event decoration; decoration; decoration services; decor services; pandal decoration; launch event; product launch; corporate event; roadshow; road show; activation; sound and light; event setup; event support; sound system hire; event equipment rental; catering coordination; booth installation
998597|Landscape care and maintenance services|gardening; gardening service; garden maintenance; landscape maintenance; lawn maintenance; lawn mowing; horticulture services; plantation; tree plantation; plant maintenance; terrace garden maintenance; garden care; landscape care; green wall maintenance; vertical garden maintenance; tree trimming; tree cutting; gardener; plant care
998598|Other information services|information services; information service
998599|Other support services|other support services; miscellaneous support; facility management; facility management services; fm services; integrated facility management

# ---------------------------------------------------------------- Agriculture support (9986)
998611|Support services to crop production|crop spraying; agricultural spraying; spraying service; drone spraying; drone spraying service; agri drone service; agricultural drone service; harvesting service; harvesting; threshing service; land preparation; ploughing service; tilling service; sowing service; seeding service; transplanting service; weeding service; crop protection service; farm services; agriculture services; agri services; farm management; farming services; irrigation service; fertigation service; crop monitoring; precision farming; precision agriculture service; soil preparation; farm mechanisation; custom hiring; custom hiring centre; drone mapping farm; farm operations
998612|Animal husbandry services|animal husbandry; dairy services; cattle services; poultry services; livestock services; artificial insemination; animal breeding
998613|Support services to hunting|hunting support
998614|Support services to forestry and logging|forestry services; logging services; afforestation services
998615|Support services to fishing|fishing services; aquaculture services; fish farming services
998619|Other support services to agriculture, hunting, forestry and fishing|other agriculture support; nursery services; greenhouse management; polyhouse management; polyhouse services; agri support; soil health service; farm automation service
998621|Support services to oil and gas extraction|oil and gas services
998622|Support services to other mining|mining services; mining support
998631|Support services to electricity transmission and distribution|power distribution services; electricity distribution support; line maintenance
998632|Support services to gas distribution|gas distribution support
998633|Support services to water distribution|water distribution support; water supply support; water supply services; water management; water management services
998634|Support services to steam, hot water and air-conditioning supply|hot water supply support

# ---------------------------------------------------------------- Manufacturing services on goods owned by others, job work (9988, 9989)
9988|Manufacturing services on physical inputs owned by others (job work)|job work; jobwork; job work charges; labour job work; processing charges; manufacturing services; contract manufacturing; processing services
998816|Other food product manufacturing services|food job work; food processing job work; milling charges; dal milling; oil extraction job work
998817|Prepared animal feeds manufacturing services|feed manufacturing job work; cattle feed job work
998821|Textile manufacturing services|textile job work; weaving job work; spinning job work; dyeing job work; knitting job work; processing of fabric
998822|Wearing apparel manufacturing services|stitching; stitching charges; tailoring; tailoring charges; garment stitching; garment job work; curtain stitching; curtain making; sofa cover stitching; embroidery job work
998831|Wood and wood product manufacturing services|wood job work; carpentry job work; woodwork job work; sawing charges; cutting charges wood; cnc wood cutting; wood cutting service; plywood cutting; panel cutting; edge banding service; laminate pressing; veneer pressing; wood processing
998832|Paper and paper product manufacturing services|paper job work; packaging job work; paper cutting; box making job work
998842|Chemical product manufacturing services|chemical job work; chemical processing
998843|Pharmaceutical product manufacturing services|pharma job work; contract manufacturing pharma
998851|Rubber product manufacturing services|rubber job work; moulding job work rubber
998852|Plastic product manufacturing services|plastic job work; injection moulding job work; plastic moulding job work; vacuum forming job work; plastic fabrication; acrylic fabrication; acrylic cutting; acrylic job work; pvc fabrication
998853|Other non-metallic mineral product manufacturing services|glass job work; glass cutting; glass processing; glass toughening; glass tempering; glass drilling; glass edging; glass polishing; stone job work; stone cutting; stone polishing; marble cutting; granite cutting; tile cutting job work; ceramic job work; cement product job work; paver block job work; glass printing; glass lamination; glass coating
998860|Basic metal manufacturing services|metal casting job work; foundry job work; rolling job work
998871|Structural metal product, tank, reservoir and steam generator manufacturing services|fabrication; fabrication work; fabrication job work; steel fabrication; ms fabrication; ss fabrication; aluminium fabrication; metal fabrication; structural fabrication; sheet metal work; sheet metal fabrication; welding work; welding job work; welding charges; structure fabrication; tank fabrication; staircase fabrication; frame fabrication; truss fabrication; steel structure job work; fabrication labour; aluminium section fabrication; window fabrication; door fabrication; cladding fabrication; acp fabrication; acp bending; acp routing; acp grooving; panel fabrication; facade fabrication; unitised facade fabrication; aluminium work; aluminium fabrication work; fabrication and powder coating
998872|Weapon and ammunition manufacturing services|ammunition job work
998873|Other fabricated metal product manufacturing and metal treatment services|powder coating; powder coating job work; galvanising; galvanizing; hot dip galvanising; anodising; anodizing; electroplating; plating; metal coating; metal treatment; heat treatment; surface treatment; sand blasting; shot blasting; metal polishing; buffing; laser cutting; laser cutting service; cnc cutting; cnc bending; bending charges; cutting charges; machining; machining charges; turning job work; milling job work; cnc machining; cnc job work; vmc job work; drilling job work; grinding job work; metal cutting; plasma cutting; waterjet cutting; punching; metal punching; press job work; sheet cutting; sheet bending; metal job work; engineering job work; pickling; passivation; electro polishing; metal finishing
998874|Computer, electronic and optical product manufacturing services|electronics job work; pcb assembly; pcba; pcb assembly service; smt assembly; electronic assembly; electronic manufacturing services; ems; circuit board assembly; pcb job work; soldering job work; electronics assembly job work; product assembly electronics
998875|Electrical equipment manufacturing services|electrical job work; panel assembly; panel assembly job work; panel fabrication; motor winding job work; transformer winding; coil winding; cable assembly; wiring harness assembly; harness job work; panel wiring job work; switchgear assembly
998876|General-purpose machinery manufacturing services|machinery job work; machine manufacturing job work; machine building
998877|Special-purpose machinery manufacturing services|special machine manufacturing; special purpose machine job work
998881|Motor vehicle and trailer manufacturing services|vehicle job work; body building; vehicle body building; trailer job work
998882|Other transport equipment manufacturing services|transport equipment job work
998891|Furniture manufacturing services|furniture job work; furniture manufacturing; modular furniture job work; furniture assembly job work; upholstery job work; carpentry manufacturing
998892|Jewellery manufacturing services|jewellery job work; gold job work; making charges
998893|Imitation jewellery manufacturing services|imitation jewellery job work
998894|Musical instrument manufacturing services|musical instrument job work
998895|Sports goods manufacturing services|sports goods job work
998896|Game and toy manufacturing services|toy job work
998897|Medical and dental instrument and supply manufacturing services|medical instrument job work
998898|Other manufacturing services|other job work; other manufacturing services
998911|Publishing, on a fee or contract basis|publishing; book publishing; publishing charges
998912|Printing and reproduction services of recorded media, on a fee or contract basis|printing; printing charges; printing service; printing services; digital printing; offset printing; flex printing; vinyl printing; banner printing; sticker printing; brochure printing; visiting card printing; screen printing; uv printing; large format printing; printing job work; photo printing service; reproduction; flyer printing; label printing; wide format printing; vinyl application; vinyl pasting; sunpack; branding printing
998920|Moulding, pressing, stamping, extruding and similar plastic manufacturing services|moulding services; moulding job work; extrusion job work; plastic pressing; stamping services; thermoforming job work
998931|Iron and steel casting services|casting job work; iron casting; steel casting
998932|Non-ferrous metal casting services|aluminium casting; brass casting; die casting job work
998933|Metal forging, pressing, stamping, roll forming and powder metallurgy services|forging job work; pressing job work metal; roll forming; stamping job work
998941|Metal waste and scrap recovery (recycling) services|scrap recovery; metal recycling; scrap processing
998942|Non-metal waste and scrap recovery (recycling) services|waste recycling; plastic recycling; paper recycling; e waste recycling; e waste

# ---------------------------------------------------------------- Transport, courier, storage and rental (96xx, 997x)
9965|Goods transport services|transport; transportation; transport charges; transportation charges; freight; freight charges; delivery; delivery charges; logistics; logistics services; cartage; carriage; carriage charges; lorry hire; truck hire; trailer hire; goods transport; shipping; shipping charges; shipment; dispatch charges; courier and freight
996511|Road transport services of goods (other than goods transport agency)|road transport; road freight; truck transport; tempo transport; tempo hire; transport by road; goods carrier; transport of goods; material transport; material transportation; material delivery; site delivery; transportation to site; freight to site; delivery to site; local transport; loading and transportation; vehicle charges; vehicle hire charges; tractor trailer hire
996512|Railway transport services of goods|rail freight; railway freight; goods train transport; rake transport
996513|Transport of petroleum, natural gas, water and other goods via pipeline|pipeline transport
996519|Other land transport services of goods|other land transport
996521|Coastal and transoceanic water transport of goods|sea freight; ocean freight; shipping by sea; sea shipment; container shipping; coastal shipping; export freight sea
996522|Inland water transport of goods|inland water transport; barge transport
996531|Air transport services of letters, parcels and other goods|air freight; air cargo; air shipment; air parcel
996532|Space transport services of freight|space freight
996601|Rental services of road vehicles with or without operator|vehicle rental; car rental; cab hire; taxi hire; bus hire; truck rental; vehicle hire; car hire; tempo rental; tempo traveller hire; bike rental; vehicle on rent; transport vehicle rental; crane rental with operator; tractor hire; tractor rental
996602|Rental services of water vessels|boat rental; vessel rental; boat hire
996603|Rental services of aircraft|aircraft rental; helicopter hire; helicopter rental
996609|Rental services of other transport vehicles|other vehicle rental
996711|Container handling services|container handling
996712|Customs House Agent services|customs clearance; cha services; customs agent; custom clearance; import clearance; export clearance; customs broker; clearing charges
996713|Clearing and forwarding services|clearing and forwarding; c and f; cfa services; forwarding services; forwarding charges; freight forwarding
996719|Other cargo and baggage handling services|loading; unloading; loading and unloading; loading charges; unloading charges; handling charges; handling; hamali; material handling; cargo handling; porter charges; shifting; shifting charges; relocation; packers and movers; moving charges; crane service; hydra hire; hydra crane; forklift hire; lifting charges; material shifting; lifting and shifting
996721|Refrigerated storage services|cold storage; refrigerated storage; cold storage charges; cold chain storage
996722|Bulk liquid or gas storage services|tank storage; bulk storage; liquid storage
996729|Other storage and warehousing services|warehousing; storage; storage charges; godown; godown rent; warehouse rent; warehouse charges; storage service; parking storage; material storage; space storage
996743|Parking lot services|parking; parking charges; parking service; car parking; parking fee
996744|Towing services for commercial and private vehicles|towing; vehicle towing; towing charges; recovery vehicle
996791|Goods transport agency services for road transport|gta; goods transport agency; transport agency; lorry receipt; lr; consignment note; transporter charges; transporter freight; gta freight; road gta
996792|Goods transport agency services for other modes of transport|gta other modes
996793|Other goods transport services|other goods transport
996811|Postal services including post office counter services|postal; post office; speed post; postage; registered post
996812|Courier services|courier; courier charges; courier service; parcel service; parcel charges; courier and postage; express delivery; speed courier; dtdc; blue dart; courier cost
996813|Local delivery services|local delivery; last mile delivery; home delivery; door delivery; delivery service; delivery boy; delivery charges local
996819|Other delivery services|other delivery
997211|Rental or leasing services involving own or leased residential property|house rent; flat rent; apartment rent; residential rent; room rent; guest house rent; villa rent; residential property rent; pg rent; rent house; home rent
997212|Rental or leasing services involving own or leased non-residential property|office rent; shop rent; commercial rent; rent; rental; rental income; showroom rent; godown rental; space rent; land rent; lease rent; property rent; building rent; factory rent; shed rent; hall rent; hall booking charges; stall rent; ground rent; commercial space rental; co working space; coworking; desk rental; hot desk; venue rental; studio rental; farm land rent; land lease
997213|Trade services of buildings|building sale; property sale; building trade
997214|Trade services of timeshare properties|timeshare
997215|Trade services of vacant and subdivided land|land sale; plot sale; land trade
997221|Property management services on a fee or contract basis|property management; building management; society management; society maintenance; maintenance charges; apartment management; facility property management
997222|Building sales on a fee or commission basis|property brokerage; real estate brokerage; brokerage building; broker commission; real estate commission; sale commission property
997223|Land sales on a fee or commission basis|land brokerage; plot brokerage
997224|Real estate appraisal services on a fee or commission basis|property valuation; valuation; valuation services; real estate valuation; property appraisal; valuation report; valuer fee
997311|Leasing or rental services concerning transport equipment including containers|container rental; trailer rental; transport equipment rental
997312|Leasing or rental services concerning agricultural machinery and equipment|tractor rental equipment; agricultural machinery rental; farm equipment rental; harvester rental; sprayer rental; drone rental; agricultural drone rental; implement rental; rotavator rental; farm machinery hire; agri equipment rental
997313|Leasing or rental services concerning construction machinery and equipment|scaffolding rental; scaffolding hire; jcb hire; jcb rental; excavator hire; excavator rental; crane rental; crane on rent; machinery rental; machinery hire; equipment rental; equipment hire; construction equipment rental; construction machinery hire; concrete mixer rental; shuttering rental; formwork rental; centering rental; compressor rental; lift rental; material lift rental; gondola rental; cradle rental; suspended platform rental; scissor lift rental; boom lift rental; aerial work platform rental; mobile tower rental; tower crane rental; crane hire; crane rental; crane on rent; crane rent
997314|Leasing or rental services concerning office machinery and equipment (except computers)|photocopier rental; printer rental; office equipment rental; copier on rent; projector rental; printer on rent; xerox machine rental
997315|Leasing or rental services concerning computers|computer rental; laptop rental; laptop on rent; desktop rental; computer on rent; server rental computers; tablet rental; ipad rental; it equipment rental
997316|Leasing or rental services concerning telecommunications equipment|telecom equipment rental; phone rental; walkie talkie rental; router rental
997319|Leasing or rental services concerning other machinery and equipment|generator rental; generator hire; dg set rental; dg rental; genset rental; pump rental; compressor hire; welding machine rental; machine rental; tools rental; tool hire; power tool rental; cctv rental; camera rental; cctv on rent; led screen rental; led wall rental; led display rental; screen rental; sound system rental; audio system rental; lighting rental; stage rental; truss rental; equipment on rent; plant rental; water tanker hire; tanker rental; ac rental; air conditioner rental; cooler rental; water purifier rental; ro rental; fan rental
997321|Leasing or rental services concerning televisions, radios, projectors, audio systems and related equipment|tv rental; television rental; projector hire; audio system hire; home entertainment rental
997322|Leasing or rental services concerning video tapes and disks|video disk rental; dvd rental
997323|Leasing or rental services concerning furniture and other household appliances|furniture rental; furniture on rent; sofa rental; chair rental; chairs on rent; table rental; tables on rent; appliance rental; household appliance rental; refrigerator rental; washing machine rental; office furniture rental; event furniture rental; mattress rental; bed rental; cot rental
997324|Leasing or rental services concerning pleasure and leisure equipment|leisure equipment rental; sports equipment rental; gym equipment rental; bicycle rental; toy rental
997325|Leasing or rental services concerning household linen|linen rental; bed linen rental; table linen rental
997326|Leasing or rental services concerning textiles, clothing and footwear|clothes rental; costume rental; dress rental; uniform rental
997327|Leasing or rental services concerning do-it-yourself machinery and equipment|diy equipment rental; hand tool rental
997329|Leasing or rental services concerning other goods|rental of goods; goods on rent; tent rental; tent hire; pandal rental; canopy rental; decoration items rental; props rental; stage props rental; carpet rental; shamiana; barricade rental; portable toilet rental; mobile toilet rental; container rental office; porta cabin rental; cabin rental; display stand rental; exhibition stall rental; kiosk rental; other rental; hire charges; rental charges; rent charges; on rent; lease
997331|Licensing services for the right to use computer software and databases|software licence; software license; licence fee; license fee; software licensing; license; licence; annual licence; annual license; software subscription fee; subscription; erp licence; erp license; crm license; crm licence; user license; user licence; per user license; cad license; autocad license; antivirus license; antivirus licence; software renewal; license renewal; licence renewal; saas licence; saas license; database license
997332|Licensing services for the right to broadcast and show original films, sound recordings and programmes|film licence; broadcast rights; content license; music license; music licence; film rights
997333|Licensing services for the right to reproduce original art works|artwork license; art licence; image license; image licence; stock image license
997334|Licensing services for the right to reprint and copy manuscripts, books, journals and periodicals|book license; reprint rights; publication rights
997335|Licensing services for the right to use R&D products|rd licence; r and d license; patent license; patent licence; technology license; technology licence; know how licence; technology transfer; patent royalty
997336|Licensing services for the right to use trademarks and franchises|trademark licence; trademark license; brand licence; brand license; franchise licence; franchise fee royalty; franchisee fee; brand royalty
997337|Licensing services for the right to use minerals including exploration and evaluation|mineral licence; mining licence; mining lease
997338|Licensing services for the right to use other natural resources including telecommunication spectrum|spectrum licence; resource license
997339|Licensing services for the right to use other intellectual property products and other resources|ip licence; ip license; intellectual property license; design license; design licence; other licence

# ---------------------------------------------------------------- Telecom, training, waste, entertainment and others
9984|Telecommunications, broadcasting and information supply services|telecom services; telecommunication; broadcasting
998413|Mobile telecommunications services|mobile services; sms services; bulk sms; mobile plan; sim charges; mobile recharge; whatsapp business api; sms gateway; voice call service; ivr; ivr service; call masking; telecom charges
998415|Data transmission services|data transmission; leased line; data connectivity; vpn; mpls; iot connectivity; m2m sim; m2m connectivity; iot sim; sim card data plan; gps tracking subscription; data plan
998422|Internet access services in wired and wireless mode|internet; internet charges; broadband; internet connection; wifi service; wi-fi service; isp services; leased internet; fibre internet; internet subscription; bandwidth; internet bandwidth
998434|Software downloads|software download; app download; digital download; downloadable software
998439|Other online contents|online content; online subscription; digital content; subscription content; ott subscription; online course subscription; e learning subscription
999293|Commercial training and coaching services|training; training charges; training fee; training program; training programme; workshop; coaching; coaching classes; classes; class; tuition; course; course fee; certification training; technical training; skill training; skill development; skill development training; vocational training; staff training; employee training; corporate training; farmer training; farmers training; agri training; product training; demo and training; user training; operator training; software training; automation training; plc training; cad training; interior design course; design course; internship; apprenticeship; webinar; online training; coaching fee
999294|Other education and training services|education services; educational services; other training; education
999210|Pre-primary education services|nursery school; kindergarten fees; pre school; preschool fee
999220|Primary education services|primary school fee; primary education
999231|Secondary education services, general|school fees; secondary school fee; high school fee
999241|Higher education services, general|college fee; university fee; tuition fee college; higher education
999295|Services involving conduct of examination for admission to educational institutions|entrance exam; exam conduct; admission test
999299|Other educational support services|educational support; study material; exam services
999311|Inpatient services|hospital charges; inpatient; hospitalisation; hospital stay
999312|Medical and dental services|medical services; doctor fee; consultation fee medical; dental services; clinic services; health check; checkup; health checkup; opd
999411|Sewerage and sewage treatment services|sewage treatment; sewerage services; stp operation; stp services; stp operation and maintenance; etp operation; effluent treatment service; sewage plant operation; stp o and m
999412|Septic tank emptying and cleaning services|septic tank cleaning; septic tank emptying; sewage cleaning; drain cleaning; drainage cleaning; manhole cleaning; sewer cleaning; drain jetting; sewage tanker
999421|Collection services of hazardous waste|hazardous waste; bio medical waste; biomedical waste collection; chemical waste collection
999422|Collection services of non-hazardous recyclable materials|scrap collection; recyclable collection; waste paper collection; plastic waste collection
999423|General waste collection services, residential|garbage collection; waste collection; domestic waste collection; door to door waste collection; residential waste
999424|General waste collection services, other|commercial waste collection; waste removal; debris removal; debris disposal; construction debris removal; rubble removal; garbage removal; waste disposal service; junk removal
999433|Non-hazardous waste treatment and disposal services|waste treatment; waste disposal; waste processing; composting service; organic waste processing
999451|Sweeping and snow removal services|sweeping; road sweeping; street sweeping; sweeping services; mechanical sweeping
999459|Other sanitation services|sanitation services; sanitation; toilet cleaning service; public toilet maintenance; toilet maintenance
999490|Other environmental protection services|environmental services; environment consulting; environmental clearance; eia; pollution control service; environmental audit; environmental monitoring; emission testing; stack monitoring; air quality monitoring service
999611|Sound recording services|sound recording; audio recording; recording studio; voice over; voiceover; dubbing; audio production; jingle; music recording
999612|Motion picture, videotape, television and radio programme production services|video production; film production; ad film; corporate film; corporate video; video making; video creation; video content creation; documentary; animation video; explainer video; promo video; product video; short film; tv production; reels production; shoot production; production services; video editing
999613|Audiovisual post-production services|post production; post-production; video editing services; animation; 2d animation; 3d animation; visual effects; vfx; motion graphics; color grading; colour grading; sound editing; audio editing; editing services
999621|Performing arts event promotion and organisation services|concert organising; show organising; event promotion; live show; cultural program; cultural event; stage show; dj night
999629|Other performing arts and live entertainment services|live entertainment; entertainment services; dj services; dj; band; music band; dance performance; anchor; anchoring; emcee; magic show; stand up; orchestra; singer services; entertainment
999631|Services of performing artists|artist fee; performer fee; actor fee; singer fee; model fee; musician fee; artist charges; talent fee; anchor fee; performing artist
999632|Services of authors, composers, sculptors and other artists except performing artists|artist services; sculptor; sculpture service; painter services; painting artist; writer services; content writing; copywriting; copy writing; content creation; blog writing; article writing; script writing; scriptwriting; illustration; illustrator; calligraphy; wall artist; mural artist; portrait painting; art work service; creative writing; technical writing
999633|Original works of authors, composers and other artists except performing artists, painters and sculptors|original work; literary work; music composition; composer; song writing
999651|Sports and recreational sports event promotion and organisation services|sports event; tournament organising; marathon organising; sports tournament; sports event management
999652|Sports and recreational sports facility operation services|sports facility; gym membership; gym fee; club membership; swimming pool charges; turf booking; court booking; ground booking; sports complex; sports club
999659|Other sports and recreational sports services|sports coaching; sports services
999662|Support services related to sports and recreation|sports support services
999691|Amusement park and similar attraction services|amusement park; water park; theme park; entry ticket; entry fee; amusement ticket; attraction ticket; fun park; entertainment park
999699|Other recreation and amusement services|recreation services; amusement services; game zone; gaming zone; party hall; recreation
9997|Other services (washing, cleaning and dyeing, beauty and well-being, funeral and miscellaneous services)|laundry; laundry services; dry cleaning; dry cleaning services; washing services; ironing services; dyeing services; linen washing; curtain cleaning; carpet washing; carpet dry cleaning; beauty parlour; beauty salon; spa; massage; salon services; hair cutting; makeup services; bridal makeup; mehendi; facial; wellness services; yoga classes; miscellaneous service; other service charges; misc charges; sundry charges; sundry services
# ---------------------------------------------------------------- Accommodation, food and beverage (9963), passenger transport (9964), financial and insurance services (9971)
9963|Accommodation, food and beverage services|accommodation; lodging; hotel services; food and beverage; food services; hospitality
996311|Room or unit accommodation services provided by hotels, inns, guest houses, clubs and the like|hotel room; hotel accommodation; room booking; hotel booking; hotel stay; room rent; guest house stay; resort stay; lodging charges; accommodation charges; stay charges
996322|Room or unit accommodation services provided by hostels, camps, paying guest and the like|hostel; hostel accommodation; paying guest; pg accommodation; dormitory; labour camp accommodation; staff accommodation
996331|Services provided by restaurants, cafes and similar eating facilities including takeaway and door delivery of food|restaurant; restaurant service; cafe; food service; food delivery; takeaway; meals; tiffin; tiffin service; lunch; breakfast; dinner; food charges; food order
996333|Services provided in canteens and other similar establishments|canteen; canteen service; staff canteen; cafeteria service; mess; mess service; canteen contract
996334|Catering services in exhibition halls, events, marriage halls and other outdoor or indoor functions|catering; catering service; catering services; event catering; wedding catering; outdoor catering; party catering; food catering; catering charges; buffet; buffet catering; function catering; caterer
996337|Other contract food services|contract food service; food supply contract; bulk food supply; food contract; meal contract
9964|Passenger transport services|passenger transport; travel services; travel; tour; tours; tour package; travel agency
996412|Taxi services including radio taxi and other similar services|taxi; cab; cab service; cab hire; taxi service; car with driver; car rental with driver; car hire with driver; outstation cab; local cab; airport taxi; taxi charges; cab charges
996413|Non-scheduled local bus and coach charter services|bus hire; bus charter; coach hire; tempo traveller hire; mini bus hire; traveller hire; staff bus; bus rental; bus on rent; employee transport
996422|Long-distance transport services of passengers through road by bus, car, non-scheduled long distance bus and coach services|bus ticket; long distance bus; outstation bus; volvo bus ticket; coach ticket
996425|Domestic or international scheduled air transport services of passengers|air ticket; flight ticket; airfare; air fare; flight booking; airline ticket; plane ticket; air travel
9971|Financial and related services|financial services; bank charges; loan processing fee; processing fee; financial charges; bank commission; commission; finance charges; finance service; financial consultancy; loan service; credit services; stock broking; brokerage
997132|Life insurance services (excluding reinsurance services)|life insurance; life insurance premium; term insurance; endowment policy; lic premium
997133|Accident and health insurance services|health insurance; medical insurance; mediclaim; accident insurance; group health insurance; personal accident insurance; health insurance premium; group mediclaim; medical policy
997134|Motor vehicle insurance services|motor insurance; vehicle insurance; car insurance; bike insurance; two wheeler insurance; commercial vehicle insurance; truck insurance; vehicle insurance premium
997136|Freight insurance services and travel insurance services|freight insurance; cargo insurance; marine insurance; transit insurance; goods in transit insurance; travel insurance; marine cargo insurance
997137|Other property insurance services|property insurance; fire insurance; building insurance; burglary insurance; contractors all risk insurance; car policy; erection all risk insurance; industrial all risk; shop insurance; office insurance; stock insurance; machinery insurance
997139|Other non-life insurance services (excluding reinsurance services)|insurance; insurance premium; insurance service; insurance charges; general insurance; liability insurance; public liability insurance; professional indemnity insurance; workmen compensation insurance; policy premium; insurance policy
997161|Insurance brokerage and agency services|insurance brokerage; insurance commission; insurance agent commission; insurance agency; policy commission
`;
